
#line 3 "lex.yy.c"

#define  YY_INT_ALIGNED short int

/* A lexical scanner generated by flex */

#define FLEX_SCANNER
#define YY_FLEX_MAJOR_VERSION 2
#define YY_FLEX_MINOR_VERSION 6
#define YY_FLEX_SUBMINOR_VERSION 4
#if YY_FLEX_SUBMINOR_VERSION > 0
#define FLEX_BETA
#endif

/* First, we deal with  platform-specific or compiler-specific issues. */

/* begin standard C headers. */
#include <stdio.h>
#include <string.h>
#include <errno.h>
#include <stdlib.h>

/* end standard C headers. */

/* flex integer type definitions */

#ifndef FLEXINT_H
#define FLEXINT_H

/* C99 systems have <inttypes.h>. Non-C99 systems may or may not. */

#if defined (__STDC_VERSION__) && __STDC_VERSION__ >= 199901L

/* C99 says to define __STDC_LIMIT_MACROS before including stdint.h,
 * if you want the limit (max/min) macros for int types. 
 */
#ifndef __STDC_LIMIT_MACROS
#define __STDC_LIMIT_MACROS 1
#endif

#include <inttypes.h>
typedef int8_t flex_int8_t;
typedef uint8_t flex_uint8_t;
typedef int16_t flex_int16_t;
typedef uint16_t flex_uint16_t;
typedef int32_t flex_int32_t;
typedef uint32_t flex_uint32_t;
#else
typedef signed char flex_int8_t;
typedef short int flex_int16_t;
typedef int flex_int32_t;
typedef unsigned char flex_uint8_t; 
typedef unsigned short int flex_uint16_t;
typedef unsigned int flex_uint32_t;

/* Limits of integral types. */
#ifndef INT8_MIN
#define INT8_MIN               (-128)
#endif
#ifndef INT16_MIN
#define INT16_MIN              (-32767-1)
#endif
#ifndef INT32_MIN
#define INT32_MIN              (-2147483647-1)
#endif
#ifndef INT8_MAX
#define INT8_MAX               (127)
#endif
#ifndef INT16_MAX
#define INT16_MAX              (32767)
#endif
#ifndef INT32_MAX
#define INT32_MAX              (2147483647)
#endif
#ifndef UINT8_MAX
#define UINT8_MAX              (255U)
#endif
#ifndef UINT16_MAX
#define UINT16_MAX             (65535U)
#endif
#ifndef UINT32_MAX
#define UINT32_MAX             (4294967295U)
#endif

#ifndef SIZE_MAX
#define SIZE_MAX               (~(size_t)0)
#endif

#endif /* ! C99 */

#endif /* ! FLEXINT_H */

/* begin standard C++ headers. */

/* TODO: this is always defined, so inline it */
#define yyconst const

#if defined(__GNUC__) && __GNUC__ >= 3
#define yynoreturn __attribute__((__noreturn__))
#else
#define yynoreturn
#endif

/* Returned upon end-of-file. */
#define YY_NULL 0

/* Promotes a possibly negative, possibly signed char to an
 *   integer in range [0..255] for use as an array index.
 */
#define YY_SC_TO_UI(c) ((YY_CHAR) (c))

/* Enter a start condition.  This macro really ought to take a parameter,
 * but we do it the disgusting crufty way forced on us by the ()-less
 * definition of BEGIN.
 */
#define BEGIN (yy_start) = 1 + 2 *
/* Translate the current start state into a value that can be later handed
 * to BEGIN to return to the state.  The YYSTATE alias is for lex
 * compatibility.
 */
#define YY_START (((yy_start) - 1) / 2)
#define YYSTATE YY_START
/* Action number for EOF rule of a given start state. */
#define YY_STATE_EOF(state) (YY_END_OF_BUFFER + state + 1)
/* Special action meaning "start processing a new file". */
#define YY_NEW_FILE yyrestart( yyin  )
#define YY_END_OF_BUFFER_CHAR 0

/* Size of default input buffer. */
#ifndef YY_BUF_SIZE
#ifdef __ia64__
/* On IA-64, the buffer size is 16k, not 8k.
 * Moreover, YY_BUF_SIZE is 2*YY_READ_BUF_SIZE in the general case.
 * Ditto for the __ia64__ case accordingly.
 */
#define YY_BUF_SIZE 32768
#else
#define YY_BUF_SIZE 16384
#endif /* __ia64__ */
#endif

/* The state buf must be large enough to hold one state per character in the main buffer.
 */
#define YY_STATE_BUF_SIZE   ((YY_BUF_SIZE + 2) * sizeof(yy_state_type))

#ifndef YY_TYPEDEF_YY_BUFFER_STATE
#define YY_TYPEDEF_YY_BUFFER_STATE
typedef struct yy_buffer_state *YY_BUFFER_STATE;
#endif

#ifndef YY_TYPEDEF_YY_SIZE_T
#define YY_TYPEDEF_YY_SIZE_T
typedef size_t yy_size_t;
#endif

extern int yyleng;

extern FILE *yyin, *yyout;

#define EOB_ACT_CONTINUE_SCAN 0
#define EOB_ACT_END_OF_FILE 1
#define EOB_ACT_LAST_MATCH 2
    
    #define YY_LESS_LINENO(n)
    #define YY_LINENO_REWIND_TO(ptr)
    
/* Return all but the first "n" matched characters back to the input stream. */
#define yyless(n) \
	do \
		{ \
		/* Undo effects of setting up yytext. */ \
        int yyless_macro_arg = (n); \
        YY_LESS_LINENO(yyless_macro_arg);\
		*yy_cp = (yy_hold_char); \
		YY_RESTORE_YY_MORE_OFFSET \
		(yy_c_buf_p) = yy_cp = yy_bp + yyless_macro_arg - YY_MORE_ADJ; \
		YY_DO_BEFORE_ACTION; /* set up yytext again */ \
		} \
	while ( 0 )
#define unput(c) yyunput( c, (yytext_ptr)  )

#ifndef YY_STRUCT_YY_BUFFER_STATE
#define YY_STRUCT_YY_BUFFER_STATE
struct yy_buffer_state
	{
	FILE *yy_input_file;

	char *yy_ch_buf;		/* input buffer */
	char *yy_buf_pos;		/* current position in input buffer */

	/* Size of input buffer in bytes, not including room for EOB
	 * characters.
	 */
	int yy_buf_size;

	/* Number of characters read into yy_ch_buf, not including EOB
	 * characters.
	 */
	int yy_n_chars;

	/* Whether we "own" the buffer - i.e., we know we created it,
	 * and can realloc() it to grow it, and should free() it to
	 * delete it.
	 */
	int yy_is_our_buffer;

	/* Whether this is an "interactive" input source; if so, and
	 * if we're using stdio for input, then we want to use getc()
	 * instead of fread(), to make sure we stop fetching input after
	 * each newline.
	 */
	int yy_is_interactive;

	/* Whether we're considered to be at the beginning of a line.
	 * If so, '^' rules will be active on the next match, otherwise
	 * not.
	 */
	int yy_at_bol;

    int yy_bs_lineno; /**< The line count. */
    int yy_bs_column; /**< The column count. */

	/* Whether to try to fill the input buffer when we reach the
	 * end of it.
	 */
	int yy_fill_buffer;

	int yy_buffer_status;

#define YY_BUFFER_NEW 0
#define YY_BUFFER_NORMAL 1
	/* When an EOF's been seen but there's still some text to process
	 * then we mark the buffer as YY_EOF_PENDING, to indicate that we
	 * shouldn't try reading from the input source any more.  We might
	 * still have a bunch of tokens to match, though, because of
	 * possible backing-up.
	 *
	 * When we actually see the EOF, we change the status to "new"
	 * (via yyrestart()), so that the user can continue scanning by
	 * just pointing yyin at a new input file.
	 */
#define YY_BUFFER_EOF_PENDING 2

	};
#endif /* !YY_STRUCT_YY_BUFFER_STATE */

/* Stack of input buffers. */
static size_t yy_buffer_stack_top = 0; /**< index of top of stack. */
static size_t yy_buffer_stack_max = 0; /**< capacity of stack. */
static YY_BUFFER_STATE * yy_buffer_stack = NULL; /**< Stack as an array. */

/* We provide macros for accessing buffer states in case in the
 * future we want to put the buffer states in a more general
 * "scanner state".
 *
 * Returns the top of the stack, or NULL.
 */
#define YY_CURRENT_BUFFER ( (yy_buffer_stack) \
                          ? (yy_buffer_stack)[(yy_buffer_stack_top)] \
                          : NULL)
/* Same as previous macro, but useful when we know that the buffer stack is not
 * NULL or when we need an lvalue. For internal use only.
 */
#define YY_CURRENT_BUFFER_LVALUE (yy_buffer_stack)[(yy_buffer_stack_top)]

/* yy_hold_char holds the character lost when yytext is formed. */
static char yy_hold_char;
static int yy_n_chars;		/* number of characters read into yy_ch_buf */
int yyleng;

/* Points to current character in buffer. */
static char *yy_c_buf_p = NULL;
static int yy_init = 0;		/* whether we need to initialize */
static int yy_start = 0;	/* start state number */

/* Flag which is used to allow yywrap()'s to do buffer switches
 * instead of setting up a fresh yyin.  A bit of a hack ...
 */
static int yy_did_buffer_switch_on_eof;

void yyrestart ( FILE *input_file  );
void yy_switch_to_buffer ( YY_BUFFER_STATE new_buffer  );
YY_BUFFER_STATE yy_create_buffer ( FILE *file, int size  );
void yy_delete_buffer ( YY_BUFFER_STATE b  );
void yy_flush_buffer ( YY_BUFFER_STATE b  );
void yypush_buffer_state ( YY_BUFFER_STATE new_buffer  );
void yypop_buffer_state ( void );

static void yyensure_buffer_stack ( void );
static void yy_load_buffer_state ( void );
static void yy_init_buffer ( YY_BUFFER_STATE b, FILE *file  );
#define YY_FLUSH_BUFFER yy_flush_buffer( YY_CURRENT_BUFFER )

YY_BUFFER_STATE yy_scan_buffer ( char *base, yy_size_t size  );
YY_BUFFER_STATE yy_scan_string ( const char *yy_str  );
YY_BUFFER_STATE yy_scan_bytes ( const char *bytes, int len  );

void *yyalloc ( yy_size_t  );
void *yyrealloc ( void *, yy_size_t  );
void yyfree ( void *  );

#define yy_new_buffer yy_create_buffer
#define yy_set_interactive(is_interactive) \
	{ \
	if ( ! YY_CURRENT_BUFFER ){ \
        yyensure_buffer_stack (); \
		YY_CURRENT_BUFFER_LVALUE =    \
            yy_create_buffer( yyin, YY_BUF_SIZE ); \
	} \
	YY_CURRENT_BUFFER_LVALUE->yy_is_interactive = is_interactive; \
	}
#define yy_set_bol(at_bol) \
	{ \
	if ( ! YY_CURRENT_BUFFER ){\
        yyensure_buffer_stack (); \
		YY_CURRENT_BUFFER_LVALUE =    \
            yy_create_buffer( yyin, YY_BUF_SIZE ); \
	} \
	YY_CURRENT_BUFFER_LVALUE->yy_at_bol = at_bol; \
	}
#define YY_AT_BOL() (YY_CURRENT_BUFFER_LVALUE->yy_at_bol)

/* Begin user sect3 */

#define yywrap() (/*CONSTCOND*/1)
#define YY_SKIP_YYWRAP
typedef flex_uint8_t YY_CHAR;

FILE *yyin = NULL, *yyout = NULL;

typedef int yy_state_type;

extern int yylineno;
int yylineno = 1;

extern char *yytext;
#ifdef yytext_ptr
#undef yytext_ptr
#endif
#define yytext_ptr yytext

static yy_state_type yy_get_previous_state ( void );
static yy_state_type yy_try_NUL_trans ( yy_state_type current_state  );
static int yy_get_next_buffer ( void );
static void yynoreturn yy_fatal_error ( const char* msg  );

/* Done after the current pattern has been matched and before the
 * corresponding action - sets up yytext.
 */
#define YY_DO_BEFORE_ACTION \
	(yytext_ptr) = yy_bp; \
	yyleng = (int) (yy_cp - yy_bp); \
	(yy_hold_char) = *yy_cp; \
	*yy_cp = '\0'; \
	(yy_c_buf_p) = yy_cp;
#define YY_NUM_RULES 126
#define YY_END_OF_BUFFER 127
/* This struct is not used in this scanner,
   but its presence is necessary. */
struct yy_trans_info
	{
	flex_int32_t yy_verify;
	flex_int32_t yy_nxt;
	};
static const flex_int16_t yy_accept[310] =
    {   0,
        0,    0,    0,    0,    0,    0,    0,    0,    0,    0,
      127,  117,  116,    1,   91,  115,    2,    4,   90,   15,
       16,    5,    7,   21,    6,   11,   23,   95,  107,  107,
       24,   22,   12,    8,   13,   14,  113,  113,   17,   18,
        3,  113,  113,  113,  113,  113,  113,  113,  113,  113,
      113,  113,  113,  113,  113,  113,  113,   19,   10,   20,
        9,  124,  123,  121,  124,  122,  126,  125,  122,   44,
      115,  115,   51,   30,   48,   45,   33,   28,   37,   26,
       38,   27,   36,    0,   94,   29,   94,   95,    0,    0,
       97,   96,  101,   97,  107,    0,  109,  108,  109,   50,

       47,   49,   39,   41,   43,   42,   40,  113,  113,    0,
       34,  113,  113,  113,  113,  113,  113,  113,  113,  113,
       74,  113,  113,  113,  113,  113,  113,   76,  113,  113,
      113,  113,  113,  113,  113,  113,  113,  113,  113,   35,
       46,  121,  120,  118,  119,  122,  115,    0,   25,   98,
       99,   99,   99,  101,  103,  102,  103,    0,    0,  110,
      111,  111,  111,   31,   32,   93,  113,  113,  113,  113,
      113,  113,  113,  113,  113,  113,  113,  113,  113,  113,
       57,  113,  113,   68,  113,  113,  113,  113,  113,  113,
      113,  113,  113,  113,  113,  113,  113,  113,  113,  113,

      118,  119,  114,   52,  100,  104,  105,  105,  105,   93,
       92,  112,  113,  113,  113,   53,  113,   81,   54,  113,
      113,  113,  113,   56,   66,  113,  113,   67,  113,   77,
      113,  113,  113,  113,  113,  113,  113,  113,  113,  113,
      113,  113,   80,  113,  113,  118,  106,   63,  113,  113,
       72,   73,  113,  113,  113,  113,   84,  113,  113,  113,
      113,   69,  113,  113,  113,  113,  113,  113,   61,  113,
      113,   62,  113,  113,  113,  113,   83,   75,   58,  113,
      113,   59,   78,   87,   60,   70,   79,  113,  113,  113,
      113,  113,  113,   55,  113,  113,   89,  113,  113,   64,

      113,   82,   86,   65,   71,   88,  113,   85,    0
    } ;

static const YY_CHAR yy_ec[256] =
    {   0,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    2,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    3,    4,    5,    1,    6,    7,    8,    9,
       10,   11,   12,   13,   14,   15,   16,   17,   18,   19,
       19,   19,   19,   19,   19,   20,   20,   21,   22,   23,
       24,   25,   26,    1,   27,   28,   29,   27,   30,   31,
       32,   32,   33,   32,   32,   34,   32,   32,   32,   32,
       32,   32,   32,   32,   35,   32,   32,   36,   32,   32,
       37,   38,   39,   40,   41,    1,   42,   43,   44,   45,

       46,   47,   48,   49,   50,   32,   51,   52,   53,   54,
       55,   56,   32,   57,   58,   59,   60,   61,   62,   63,
       64,   65,   66,   67,   68,   69,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,

        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1
    } ;

static const YY_CHAR yy_meta[70] =
    {   0,
        1,    2,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    3,    3,    3,    3,
        1,    1,    1,    1,    1,    1,    3,    3,    3,    3,
        3,    4,    4,    5,    5,    4,    1,    1,    1,    1,
        4,    3,    3,    3,    3,    3,    3,    4,    4,    4,
        4,    5,    4,    4,    4,    4,    4,    4,    4,    5,
        4,    4,    4,    4,    4,    1,    1,    1,    1
    } ;

static const flex_int16_t yy_base[319] =
    {   0,
        0,    0,   68,   69,   72,   73,    0,    0,   74,   75,
      259, 1367, 1367,  234, 1367,  240,   63,   71, 1367, 1367,
     1367,  230,   67, 1367,   72,   83,  227,   97,  146,   59,
      225, 1367,   98,  224,   68, 1367,  106,  122, 1367, 1367,
      222,  150,  127,  133,  154,  182,  193,  197,  202,  206,
      212,  216,  221,  246,  255,  259,  135, 1367,   61, 1367,
     1367, 1367, 1367,  193,  225,  174, 1367, 1367,  170, 1367,
      180,   93,  185, 1367, 1367, 1367, 1367, 1367, 1367, 1367,
     1367, 1367, 1367,  174,  267, 1367,  272,   93,  278,  106,
      234,   96,  247,  265,  108,  301,  267,  125,  270, 1367,

     1367, 1367,  164, 1367, 1367, 1367,  158,    0,  279,  314,
     1367,  287,  295,  302,  309,  316,  323,  327,  334,  345,
      341,  356,  349,  363,  371,  378,  382,  389,  393,  400,
      408,  414,  429,  433,  422,  437,  448,  452,  459, 1367,
     1367, 1367, 1367,  498,    0, 1367,  171,  141, 1367,  158,
     1367,  124,  103,  478,  485,  301,  288,  505,  509,  401,
     1367,  101,   61, 1367, 1367,  514,  487,  498,  512,  514,
      516,  531,  535,  537,  556,  558,  554,  572,  577,  588,
      583,  594,  602,  608,  623,  616,  627,  631,  638,  649,
      655,  657,  663,  671,  678,  686,  693,  701,  707,  709,

      592,    0,   94, 1367, 1367,  425, 1367,   65,   42,  755,
     1367, 1367,  728,  732,  747,  749,  754,  765,  769,  771,
      773,  787,  789,  793,  795,  809,  811,  813,  815,  829,
      831,  835,  846,  850,  852,  866,  868,  882,  889,  897,
      903,  918,  911,  922,  929, 1367, 1367,  933,  937,  944,
      948,  952,  959,  967,  974,  978,  985,  992,  996, 1000,
     1007, 1014, 1022, 1028, 1030, 1036, 1044, 1050, 1052, 1066,
     1068, 1072, 1083, 1087, 1094, 1089, 1108, 1110, 1112, 1127,
     1131, 1129, 1133, 1135, 1149, 1151, 1153, 1157, 1168, 1172,
     1176, 1187, 1194, 1183, 1198, 1202, 1209, 1217, 1223, 1225,

     1231, 1242, 1246, 1248, 1250, 1264, 1266, 1270, 1367, 1332,
     1337, 1342, 1347, 1350, 1355, 1358, 1361,   87
    } ;

static const flex_int16_t yy_def[319] =
    {   0,
      309,    1,  310,  310,  310,  310,  311,  311,  312,  312,
      309,  309,  309,  309,  309,  313,  309,  309,  309,  309,
      309,  309,  309,  309,  309,  309,  309,  309,  309,   29,
      309,  309,  309,  309,  309,  309,  314,  314,  309,  309,
      309,  314,  314,  314,  314,  314,  314,  314,  314,  314,
      314,  314,  314,  314,  314,  314,   53,  309,  309,  309,
      309,  309,  309,  309,  315,  309,  309,  309,  309,  309,
      313,  313,  309,  309,  309,  309,  309,  309,  309,  309,
      309,  309,  309,  309,  309,  309,  309,   28,  309,  309,
      309,  309,  316,  309,   29,  309,  309,  309,  309,  309,

      309,  309,  309,  309,  309,  309,  309,  317,   53,  309,
      309,   53,   53,   53,   53,   53,   53,   53,   53,   53,
       53,   53,   53,   53,   53,   53,   53,   53,   53,   53,
       53,   53,   53,   53,   53,   53,   53,   53,   53,  309,
      309,  309,  309,  309,  318,  309,  313,  309,  309,  309,
      309,  309,  309,  316,  309,  309,  309,  309,  309,  309,
      309,  309,  309,  309,  309,  309,   53,   53,   53,   53,
       53,   53,   53,   53,   53,   53,   53,   53,   53,   53,
       53,   53,   53,   53,   53,   53,   53,   53,   53,   53,
       53,   53,   53,   53,   53,   53,   53,   53,   53,   53,

      309,  318,  313,  309,  309,  309,  309,  309,  309,  309,
      309,  309,   53,   53,   53,   53,   53,   53,   53,   53,
       53,   53,   53,   53,   53,   53,   53,   53,   53,   53,
       53,   53,   53,   53,   53,   53,   53,   53,   53,   53,
       53,   53,   53,   53,   53,  309,  309,   53,   53,   53,
       53,   53,   53,   53,   53,   53,   53,   53,   53,   53,
       53,   53,   53,   53,   53,   53,   53,   53,   53,   53,
       53,   53,   53,   53,   53,   53,   53,   53,   53,   53,
       53,   53,   53,   53,   53,   53,   53,   53,   53,   53,
       53,   53,   53,   53,   53,   53,   53,   53,   53,   53,

       53,   53,   53,   53,   53,   53,   53,   53,    0,  309,
      309,  309,  309,  309,  309,  309,  309,  309
    } ;

static const flex_int16_t yy_nxt[1437] =
    {   0,
       12,   13,   14,   15,   16,   17,   18,   19,   20,   21,
       22,   23,   24,   25,   26,   27,   28,   29,   30,   30,
       31,   32,   33,   34,   35,   36,   37,   37,   37,   38,
       37,   37,   37,   37,   37,   37,   39,   12,   40,   41,
       42,   43,   44,   45,   46,   47,   48,   49,   37,   50,
       37,   51,   37,   37,   37,   37,   52,   53,   54,   55,
       56,   57,   37,   37,   37,   58,   59,   60,   61,   63,
       63,   64,   64,   63,   63,   67,   67,   76,   79,   66,
       66,   69,   69,   73,  140,   81,   74,   75,   90,  202,
       80,  106,  107,  247,   77,   82,   83,   84,  247,   85,

       85,   85,   85,  101,   90,   65,   65,   72,   72,   65,
       65,   87,  212,   88,   88,   88,   89,  110,  102,  110,
      103,  104,  108,  108,  108,  108,   90,  141,  309,  152,
       91,   92,   93,  110,  212,  110,  147,   90,  108,  108,
      108,  108,   90,  108,  108,  108,  108,  153,   94,  108,
      108,  108,  108,   90,  205,  309,   92,  205,  162,   93,
       87,  204,   95,   95,   95,   95,  108,  108,  108,  108,
      108,  108,  108,  108,  203,   96,  163,  112,  113,   97,
       98,  165,  114,  139,  109,   72,  115,  164,  149,  116,
      148,   96,  205,  109,   72,  117,  109,   99,  108,  108,

      108,  108,  118,  146,  110,   98,  110,  146,  119,  108,
      108,  108,  108,  108,  108,  108,  108,  205,  108,  108,
      108,  108,  108,  108,  108,  108,  142,  120,  108,  108,
      108,  108,  108,  108,  108,  108,  121,  108,  108,  108,
      108,  144,  144,  144,  122,  111,  123,  105,  125,  100,
       86,  126,  128,   78,   72,  124,  127,   70,  309,  129,
      309,  131,  108,  108,  108,  108,  130,  150,  151,  132,
      133,  108,  108,  108,  108,  108,  108,  108,  108,  134,
      155,  156,  135,   85,   85,   85,   85,  145,   85,   85,
       85,   85,   87,  151,   89,   89,   89,   89,  157,  151,

      160,  161,  309,  309,  161,  309,  156,   90,  137,  136,
      309,  309,  158,  138,  158,  309,  150,  159,  159,  159,
      159,  160,  207,   90,  151,  309,  161,  109,  109,  161,
      166,  166,  166,  166,  208,  109,  109,  109,  309,  206,
      109,  167,  309,  109,  109,  109,  309,  207,  109,  168,
      109,  109,  209,  109,  169,  309,  109,  109,  109,  309,
      109,  171,  309,  109,  109,  109,  309,  170,  173,  309,
      109,  109,  109,  309,  109,  109,  109,  109,  309,  309,
      172,  109,  109,  109,  109,  109,  309,  174,  109,  109,
      109,  175,  109,  109,  109,  109,  309,  109,  109,  109,

      176,  309,  109,  109,  109,  109,  109,  109,  178,  309,
      109,  109,  109,  177,  109,  309,  309,  109,  309,  109,
      109,  179,  309,  309,  109,  180,  109,  109,  309,  109,
      109,  109,  109,  309,  181,  212,  109,  109,  109,  109,
      182,  109,  109,  109,  183,  309,  309,  109,  109,  109,
      109,  184,  309,  185,  109,  186,  109,  109,  109,  247,
      212,  109,  109,  109,  309,  187,  188,  309,  189,  109,
      109,  194,  109,  309,  192,  109,  190,  109,  109,  309,
      109,  109,  109,  109,  247,  109,  109,  109,  309,  193,
      109,  109,  195,  191,  109,  109,  109,  196,  109,  309,

      109,  198,  309,  199,  309,  197,  109,  109,  200,  109,
      109,  155,  156,  109,  201,  201,  201,  109,  206,  207,
      109,  210,  210,  210,  210,  159,  159,  159,  159,  157,
      166,  166,  166,  166,  309,  109,  109,  156,  309,  211,
      309,  213,  309,  309,  207,  109,  109,  109,  109,  309,
      214,  309,  309,  215,  309,  211,  109,  217,  309,  109,
      109,  109,  109,  109,  109,  109,  309,  309,  216,  309,
      109,  309,  109,  109,  109,  109,  218,  109,  309,  109,
      109,  309,  309,  109,  109,  109,  109,  309,  309,  109,
      309,  219,  109,  109,  220,  221,  109,  222,  109,  224,

      223,  309,  109,  109,  109,  109,  109,  109,  246,  246,
      246,  309,  109,  309,  109,  109,  109,  109,  309,  109,
      109,  109,  226,  309,  225,  109,  109,  309,  309,  227,
      109,  109,  109,  109,  309,  109,  109,  109,  109,  309,
      309,  109,  109,  109,  109,  309,  109,  309,  228,  109,
      109,  229,  109,  309,  309,  109,  109,  109,  309,  309,
      109,  309,  309,  109,  109,  231,  109,  309,  309,  109,
      230,  109,  109,  309,  109,  109,  109,  109,  309,  109,
      109,  109,  309,  309,  109,  232,  109,  109,  109,  109,
      233,  309,  109,  309,  234,  309,  109,  109,  109,  109,

      236,  309,  235,  109,  109,  109,  109,  109,  309,  309,
      109,  109,  109,  109,  309,  237,  109,  309,  109,  109,
      109,  109,  238,  240,  109,  309,  109,  109,  309,  239,
      309,  309,  109,  309,  109,  109,  109,  309,  309,  109,
      241,  109,  242,  309,  109,  243,  309,  109,  244,  109,
      109,  109,  309,  309,  109,  109,  109,  109,  109,  109,
      245,  309,  109,  309,  309,  109,  309,  109,  109,  309,
      109,  210,  210,  210,  210,  309,  109,  109,  309,  248,
      109,  109,  309,  309,  309,  211,  109,  249,  309,  109,
      109,  309,  309,  109,  250,  109,  109,  109,  109,  309,

      309,  211,  109,  109,  251,  109,  309,  109,  109,  309,
      109,  309,  109,  109,  109,  109,  309,  109,  109,  109,
      109,  109,  253,  109,  309,  309,  109,  109,  309,  252,
      109,  109,  109,  309,  109,  109,  109,  109,  109,  309,
      255,  109,  109,  109,  109,  109,  254,  109,  109,  309,
      109,  109,  309,  109,  109,  309,  109,  109,  109,  109,
      109,  109,  109,  109,  109,  256,  309,  109,  258,  257,
      109,  109,  109,  109,  109,  309,  109,  109,  109,  109,
      109,  309,  309,  109,  109,  309,  309,  109,  259,  109,
      109,  260,  109,  109,  109,  109,  109,  263,  109,  109,

      109,  109,  261,  309,  109,  309,  309,  109,  262,  309,
      109,  109,  309,  109,  109,  109,  109,  265,  309,  309,
      264,  309,  309,  309,  109,  266,  109,  109,  309,  109,
      109,  109,  267,  309,  309,  309,  309,  109,  109,  309,
      109,  268,  309,  109,  309,  109,  109,  109,  309,  309,
      109,  109,  109,  309,  309,  109,  269,  309,  109,  109,
      109,  109,  309,  309,  109,  270,  109,  109,  309,  109,
      109,  109,  109,  309,  272,  309,  109,  109,  109,  109,
      271,  109,  109,  109,  309,  109,  109,  109,  273,  309,
      109,  109,  109,  274,  109,  109,  109,  109,  109,  309,

      109,  109,  109,  309,  309,  109,  109,  109,  109,  109,
      109,  309,  275,  109,  309,  109,  109,  109,  276,  277,
      109,  309,  109,  109,  309,  109,  109,  109,  109,  309,
      309,  278,  109,  109,  109,  109,  109,  279,  309,  109,
      109,  109,  309,  109,  109,  109,  109,  309,  109,  281,
      109,  309,  309,  109,  280,  109,  109,  109,  109,  309,
      282,  109,  109,  109,  309,  109,  283,  309,  109,  309,
      109,  109,  109,  285,  284,  109,  109,  109,  109,  109,
      109,  309,  309,  109,  109,  109,  109,  309,  109,  109,
      309,  109,  287,  109,  286,  288,  309,  109,  109,  109,

      109,  109,  109,  309,  309,  109,  309,  309,  109,  309,
      109,  109,  309,  109,  109,  109,  109,  290,  309,  289,
      109,  109,  309,  309,  109,  309,  109,  109,  291,  109,
      109,  109,  109,  109,  309,  109,  109,  109,  109,  309,
      292,  109,  109,  109,  109,  109,  309,  294,  109,  309,
      109,  309,  109,  293,  309,  109,  109,  109,  109,  109,
      109,  109,  309,  309,  309,  309,  109,  309,  109,  109,
      109,  109,  295,  109,  296,  109,  109,  109,  109,  109,
      109,  109,  109,  109,  109,  109,  309,  109,  109,  109,
      109,  109,  109,  109,  109,  309,  109,  109,  109,  109,

      109,  109,  109,  297,  309,  109,  109,  109,  309,  109,
      109,  109,  109,  298,  109,  109,  109,  109,  109,  309,
      109,  109,  309,  299,  109,  109,  109,  309,  301,  109,
      109,  109,  109,  109,  109,  109,  109,  109,  300,  302,
      309,  109,  109,  109,  109,  109,  109,  109,  109,  309,
      109,  109,  109,  309,  303,  109,  109,  109,  109,  109,
      304,  305,  309,  109,  309,  109,  109,  109,  306,  309,
      109,  109,  109,  109,  109,  109,  309,  309,  109,  109,
      109,  109,  309,  109,  109,  309,  109,  307,  309,  109,
      109,  109,  109,  309,  109,  109,  109,  109,  109,  109,

      109,  309,  309,  109,  109,  309,  109,  109,  109,  109,
      309,  109,  109,  109,  109,  109,  309,  309,  109,  109,
      309,  309,  109,  309,  109,  109,  309,  109,  109,  308,
      309,  109,   62,   62,   62,   62,   62,   67,   67,   67,
       67,   67,   68,   68,   68,   68,   68,   71,  309,   71,
       71,   71,  109,  109,  109,  143,  309,  143,  143,  143,
      154,  309,  154,  108,  108,  108,   11,  309,  309,  309,
      309,  309,  309,  309,  309,  309,  309,  309,  309,  309,
      309,  309,  309,  309,  309,  309,  309,  309,  309,  309,
      309,  309,  309,  309,  309,  309,  309,  309,  309,  309,

      309,  309,  309,  309,  309,  309,  309,  309,  309,  309,
      309,  309,  309,  309,  309,  309,  309,  309,  309,  309,
      309,  309,  309,  309,  309,  309,  309,  309,  309,  309,
      309,  309,  309,  309,  309,  309
    } ;

static const flex_int16_t yy_chk[1437] =
    {   0,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    3,
        4,    3,    4,    5,    6,    9,   10,   18,   23,    5,
        6,    9,   10,   17,   59,   25,   17,   17,   30,  318,
       23,   35,   35,  209,   18,   25,   25,   26,  208,   26,

       26,   26,   26,   33,   30,    3,    4,   72,  203,    5,
        6,   28,  163,   28,   28,   28,   28,   90,   33,   90,
       33,   33,   37,   37,   37,   37,   28,   59,   88,   92,
       28,   28,   28,   38,  162,   38,   72,   95,   38,   38,
       38,   38,   28,   43,   43,   43,   43,   92,   28,   44,
       44,   44,   44,   95,  153,   88,   28,  152,   98,   28,
       29,  148,   29,   29,   29,   29,   42,   42,   42,   42,
       45,   45,   45,   45,  147,   29,   98,   42,   42,   29,
       29,  107,   42,   57,   57,  147,   43,  103,   84,   44,
       73,   29,  150,   57,   71,   45,   57,   29,   46,   46,

       46,   46,   45,   69,   47,   29,   47,   66,   45,   47,
       47,   47,   47,   48,   48,   48,   48,  150,   49,   49,
       49,   49,   50,   50,   50,   50,   64,   46,   51,   51,
       51,   51,   52,   52,   52,   52,   46,   53,   53,   53,
       53,   65,   65,   65,   47,   41,   47,   34,   48,   31,
       27,   48,   50,   22,   16,   47,   49,   14,   11,   50,
        0,   52,   54,   54,   54,   54,   51,   91,   91,   53,
       53,   55,   55,   55,   55,   56,   56,   56,   56,   53,
       93,   93,   53,   85,   85,   85,   85,   65,   87,   87,
       87,   87,   89,   91,   89,   89,   89,   89,   93,   94,

       97,   97,    0,    0,   99,    0,   93,   89,   55,   54,
        0,    0,   96,   56,   96,    0,   94,   96,   96,   96,
       96,   99,  157,   89,   94,    0,   97,  109,  109,   99,
      110,  110,  110,  110,  156,  112,  112,  109,    0,  157,
      109,  112,    0,  113,  113,  112,    0,  157,  112,  113,
      114,  114,  156,  113,  114,    0,  113,  115,  115,    0,
      114,  116,    0,  114,  116,  116,    0,  115,  118,    0,
      115,  117,  117,    0,  116,  118,  118,  116,    0,    0,
      117,  117,  119,  119,  117,  118,    0,  119,  118,  121,
      121,  120,  119,  120,  120,  119,    0,  123,  123,  121,

      121,    0,  121,  120,  122,  122,  120,  123,  123,    0,
      123,  124,  124,  122,  122,    0,    0,  122,    0,  125,
      125,  124,    0,    0,  124,  125,  126,  126,    0,  125,
      127,  127,  125,    0,  126,  160,  126,  128,  128,  126,
      127,  129,  129,  127,  129,    0,    0,  128,  130,  130,
      128,  129,    0,  130,  129,  131,  131,  131,  130,  206,
      160,  130,  132,  132,    0,  131,  131,    0,  132,  131,
      135,  135,  132,    0,  134,  132,  133,  133,  133,    0,
      135,  134,  134,  135,  206,  136,  136,  133,    0,  134,
      133,  134,  136,  133,  134,  136,  137,  137,  136,    0,

      138,  138,    0,  138,    0,  137,  137,  139,  139,  137,
      138,  154,  154,  138,  144,  144,  144,  139,  155,  155,
      139,  158,  158,  158,  158,  159,  159,  159,  159,  154,
      166,  166,  166,  166,    0,  167,  167,  154,    0,  159,
        0,  167,    0,    0,  155,  167,  168,  168,  167,    0,
      168,    0,    0,  169,    0,  159,  168,  171,    0,  168,
      169,  169,  170,  170,  171,  171,    0,    0,  170,    0,
      169,    0,  170,  169,  171,  170,  172,  171,    0,  172,
      172,    0,    0,  173,  173,  174,  174,    0,    0,  172,
        0,  173,  172,  173,  174,  174,  173,  175,  174,  177,

      176,    0,  177,  177,  175,  175,  176,  176,  201,  201,
      201,    0,  177,    0,  175,  177,  176,  175,    0,  176,
      178,  178,  179,    0,  178,  179,  179,    0,    0,  180,
      178,  181,  181,  178,    0,  179,  180,  180,  179,    0,
        0,  181,  182,  182,  181,    0,  180,    0,  182,  180,
      183,  183,  182,    0,    0,  182,  184,  184,    0,    0,
      183,    0,    0,  183,  186,  186,  184,    0,    0,  184,
      185,  185,  185,    0,  186,  187,  187,  186,    0,  188,
      188,  185,    0,    0,  185,  187,  189,  189,  187,  188,
      188,    0,  188,    0,  189,    0,  189,  190,  190,  189,

      191,    0,  190,  191,  191,  192,  192,  190,    0,    0,
      190,  193,  193,  191,    0,  192,  191,    0,  192,  194,
      194,  193,  193,  195,  193,    0,  195,  195,    0,  194,
        0,    0,  194,    0,  196,  196,  195,    0,    0,  195,
      196,  197,  197,    0,  196,  198,    0,  196,  199,  198,
      198,  197,    0,    0,  197,  199,  199,  200,  200,  198,
      200,    0,  198,    0,    0,  199,    0,  200,  199,    0,
      200,  210,  210,  210,  210,    0,  213,  213,    0,  213,
      214,  214,    0,    0,    0,  210,  213,  214,    0,  213,
      214,    0,    0,  214,  215,  215,  215,  216,  216,    0,

        0,  210,  217,  217,  217,  215,    0,  216,  215,    0,
      216,    0,  217,  218,  218,  217,    0,  219,  219,  220,
      220,  221,  221,  218,    0,    0,  218,  219,    0,  220,
      219,  221,  220,    0,  221,  222,  222,  223,  223,    0,
      223,  224,  224,  225,  225,  222,  222,  223,  222,    0,
      223,  224,    0,  225,  224,    0,  225,  226,  226,  227,
      227,  228,  228,  229,  229,  226,    0,  226,  229,  227,
      226,  228,  227,  229,  228,    0,  229,  230,  230,  231,
      231,    0,    0,  232,  232,    0,    0,  230,  231,  231,
      230,  232,  231,  232,  233,  233,  232,  235,  234,  234,

      235,  235,  233,    0,  233,    0,    0,  233,  234,    0,
      235,  234,    0,  235,  236,  236,  237,  237,    0,    0,
      236,    0,    0,    0,  236,  238,  237,  236,    0,  237,
      238,  238,  239,    0,    0,    0,    0,  239,  239,    0,
      238,  240,    0,  238,    0,  240,  240,  239,    0,    0,
      239,  241,  241,    0,    0,  240,  241,    0,  240,  243,
      243,  241,    0,    0,  241,  242,  242,  242,    0,  243,
      244,  244,  243,    0,  245,    0,  242,  245,  245,  242,
      244,  248,  248,  244,    0,  249,  249,  245,  249,    0,
      245,  248,  250,  250,  248,  249,  251,  251,  249,    0,

      252,  252,  250,    0,    0,  250,  251,  253,  253,  251,
      252,    0,  253,  252,    0,  254,  254,  253,  254,  255,
      253,    0,  255,  255,    0,  254,  256,  256,  254,    0,
        0,  256,  255,  257,  257,  255,  256,  258,    0,  256,
      258,  258,    0,  257,  259,  259,  257,    0,  260,  260,
      258,    0,    0,  258,  259,  261,  261,  259,  260,    0,
      261,  260,  262,  262,    0,  261,  263,    0,  261,    0,
      263,  263,  262,  265,  264,  262,  264,  264,  265,  265,
      263,    0,    0,  263,  266,  266,  264,    0,  265,  264,
        0,  265,  267,  267,  266,  268,    0,  266,  268,  268,

      269,  269,  267,    0,    0,  267,    0,    0,  268,    0,
      269,  268,    0,  269,  270,  270,  271,  271,    0,  270,
      272,  272,    0,    0,  270,    0,  271,  270,  273,  271,
      272,  273,  273,  272,    0,  274,  274,  276,  276,    0,
      274,  273,  275,  275,  273,  274,    0,  276,  274,    0,
      276,    0,  275,  275,    0,  275,  277,  277,  278,  278,
      279,  279,    0,    0,    0,    0,  277,    0,  278,  277,
      279,  278,  280,  279,  281,  280,  280,  282,  282,  281,
      281,  283,  283,  284,  284,  280,    0,  282,  280,  281,
      282,  283,  281,  284,  283,    0,  284,  285,  285,  286,

      286,  287,  287,  288,    0,  288,  288,  285,    0,  286,
      285,  287,  286,  289,  287,  288,  289,  289,  288,    0,
      290,  290,    0,  290,  291,  291,  289,    0,  292,  289,
      290,  294,  294,  290,  291,  292,  292,  291,  291,  293,
        0,  294,  293,  293,  294,  292,  295,  295,  292,    0,
      296,  296,  293,    0,  295,  293,  295,  297,  297,  295,
      296,  298,    0,  296,    0,  298,  298,  297,  299,    0,
      297,  299,  299,  300,  300,  298,    0,    0,  298,  301,
      301,  299,    0,  300,  299,    0,  300,  301,    0,  301,
      302,  302,  301,    0,  303,  303,  304,  304,  305,  305,

      302,    0,    0,  302,  303,    0,  304,  303,  305,  304,
        0,  305,  306,  306,  307,  307,    0,    0,  308,  308,
        0,    0,  306,    0,  307,  306,    0,  307,  308,  307,
        0,  308,  310,  310,  310,  310,  310,  311,  311,  311,
      311,  311,  312,  312,  312,  312,  312,  313,    0,  313,
      313,  313,  314,  314,  314,  315,    0,  315,  315,  315,
      316,    0,  316,  317,  317,  317,  309,  309,  309,  309,
      309,  309,  309,  309,  309,  309,  309,  309,  309,  309,
      309,  309,  309,  309,  309,  309,  309,  309,  309,  309,
      309,  309,  309,  309,  309,  309,  309,  309,  309,  309,

      309,  309,  309,  309,  309,  309,  309,  309,  309,  309,
      309,  309,  309,  309,  309,  309,  309,  309,  309,  309,
      309,  309,  309,  309,  309,  309,  309,  309,  309,  309,
      309,  309,  309,  309,  309,  309
    } ;

static yy_state_type yy_last_accepting_state;
static char *yy_last_accepting_cpos;

extern int yy_flex_debug;
int yy_flex_debug = 0;

/* The intent behind this definition is that it'll catch
 * any uses of REJECT which flex missed.
 */
#define REJECT reject_used_but_not_detected
#define yymore() yymore_used_but_not_detected
#define YY_MORE_ADJ 0
#define YY_RESTORE_YY_MORE_OFFSET
char *yytext;
#line 1 "clexer.l"
#line 4 "clexer.l"
#include <string.h>
#define OP 257
#define FILEN 258
#define IDENT 259
#define KEYWD 260
#define CHAR  261
#define STRING 262
#define INT 265
#define FLOAT 266
#define DOUBLE 267


char string[4096];
int pos = 0;
typedef union {
	int integer;
	char value[9];
	char *string_literal;
	int pos;
	float f;
	double d;
} YYSTYPE;

YYSTYPE  yylval;
char file_name[300];
int line=1;
#line 892 "lex.yy.c"

#line 894 "lex.yy.c"

#define INITIAL 0
#define STRESC 1
#define CHRESC 2
#define SIGN 3
#define ENDCHR 4

#ifndef YY_NO_UNISTD_H
/* Special case for "unistd.h", since it is non-ANSI. We include it way
 * down here because we want the user's section 1 to have been scanned first.
 * The user has a chance to override it with an option.
 */
#include <unistd.h>
#endif

#ifndef YY_EXTRA_TYPE
#define YY_EXTRA_TYPE void *
#endif

static int yy_init_globals ( void );

/* Accessor methods to globals.
   These are made visible to non-reentrant scanners for convenience. */

int yylex_destroy ( void );

int yyget_debug ( void );

void yyset_debug ( int debug_flag  );

YY_EXTRA_TYPE yyget_extra ( void );

void yyset_extra ( YY_EXTRA_TYPE user_defined  );

FILE *yyget_in ( void );

void yyset_in  ( FILE * _in_str  );

FILE *yyget_out ( void );

void yyset_out  ( FILE * _out_str  );

			int yyget_leng ( void );

char *yyget_text ( void );

int yyget_lineno ( void );

void yyset_lineno ( int _line_number  );

/* Macros after this point can all be overridden by user definitions in
 * section 1.
 */

#ifndef YY_SKIP_YYWRAP
#ifdef __cplusplus
extern "C" int yywrap ( void );
#else
extern int yywrap ( void );
#endif
#endif

#ifndef YY_NO_UNPUT
    
    static void yyunput ( int c, char *buf_ptr  );
    
#endif

#ifndef yytext_ptr
static void yy_flex_strncpy ( char *, const char *, int );
#endif

#ifdef YY_NEED_STRLEN
static int yy_flex_strlen ( const char * );
#endif

#ifndef YY_NO_INPUT
#ifdef __cplusplus
static int yyinput ( void );
#else
static int input ( void );
#endif

#endif

/* Amount of stuff to slurp up with each read. */
#ifndef YY_READ_BUF_SIZE
#ifdef __ia64__
/* On IA-64, the buffer size is 16k, not 8k */
#define YY_READ_BUF_SIZE 16384
#else
#define YY_READ_BUF_SIZE 8192
#endif /* __ia64__ */
#endif

/* Copy whatever the last rule matched to the standard output. */
#ifndef ECHO
/* This used to be an fputs(), but since the string might contain NUL's,
 * we now use fwrite().
 */
#define ECHO do { if (fwrite( yytext, (size_t) yyleng, 1, yyout )) {} } while (0)
#endif

/* Gets input and stuffs it into "buf".  number of characters read, or YY_NULL,
 * is returned in "result".
 */
#ifndef YY_INPUT
#define YY_INPUT(buf,result,max_size) \
	if ( YY_CURRENT_BUFFER_LVALUE->yy_is_interactive ) \
		{ \
		int c = '*'; \
		int n; \
		for ( n = 0; n < max_size && \
			     (c = getc( yyin )) != EOF && c != '\n'; ++n ) \
			buf[n] = (char) c; \
		if ( c == '\n' ) \
			buf[n++] = (char) c; \
		if ( c == EOF && ferror( yyin ) ) \
			YY_FATAL_ERROR( "input in flex scanner failed" ); \
		result = n; \
		} \
	else \
		{ \
		errno=0; \
		while ( (result = (int) fread(buf, 1, (yy_size_t) max_size, yyin)) == 0 && ferror(yyin)) \
			{ \
			if( errno != EINTR) \
				{ \
				YY_FATAL_ERROR( "input in flex scanner failed" ); \
				break; \
				} \
			errno=0; \
			clearerr(yyin); \
			} \
		}\
\

#endif

/* No semi-colon after return; correct usage is to write "yyterminate();" -
 * we don't want an extra ';' after the "return" because that will cause
 * some compilers to complain about unreachable statements.
 */
#ifndef yyterminate
#define yyterminate() return YY_NULL
#endif

/* Number of entries by which start-condition stack grows. */
#ifndef YY_START_STACK_INCR
#define YY_START_STACK_INCR 25
#endif

/* Report a fatal error. */
#ifndef YY_FATAL_ERROR
#define YY_FATAL_ERROR(msg) yy_fatal_error( msg )
#endif

/* end tables serialization structures and prototypes */

/* Default declaration of generated scanner - a define so the user can
 * easily add parameters.
 */
#ifndef YY_DECL
#define YY_DECL_IS_OURS 1

extern int yylex (void);

#define YY_DECL int yylex (void)
#endif /* !YY_DECL */

/* Code executed at the beginning of each rule, after yytext and yyleng
 * have been set up.
 */
#ifndef YY_USER_ACTION
#define YY_USER_ACTION
#endif

/* Code executed at the end of each rule. */
#ifndef YY_BREAK
#define YY_BREAK /*LINTED*/break;
#endif

#define YY_RULE_SETUP \
	YY_USER_ACTION

/** The main scanner function which does all the work.
 */
YY_DECL
{
	yy_state_type yy_current_state;
	char *yy_cp, *yy_bp;
	int yy_act;
    
	if ( !(yy_init) )
		{
		(yy_init) = 1;

#ifdef YY_USER_INIT
		YY_USER_INIT;
#endif

		if ( ! (yy_start) )
			(yy_start) = 1;	/* first start state */

		if ( ! yyin )
			yyin = stdin;

		if ( ! yyout )
			yyout = stdout;

		if ( ! YY_CURRENT_BUFFER ) {
			yyensure_buffer_stack ();
			YY_CURRENT_BUFFER_LVALUE =
				yy_create_buffer( yyin, YY_BUF_SIZE );
		}

		yy_load_buffer_state(  );
		}

	{
#line 39 "clexer.l"


#line 1118 "lex.yy.c"

	while ( /*CONSTCOND*/1 )		/* loops until end-of-file is reached */
		{
		yy_cp = (yy_c_buf_p);

		/* Support of yytext. */
		*yy_cp = (yy_hold_char);

		/* yy_bp points to the position in yy_ch_buf of the start of
		 * the current run.
		 */
		yy_bp = yy_cp;

		yy_current_state = (yy_start);
yy_match:
		do
			{
			YY_CHAR yy_c = yy_ec[YY_SC_TO_UI(*yy_cp)] ;
			if ( yy_accept[yy_current_state] )
				{
				(yy_last_accepting_state) = yy_current_state;
				(yy_last_accepting_cpos) = yy_cp;
				}
			while ( yy_chk[yy_base[yy_current_state] + yy_c] != yy_current_state )
				{
				yy_current_state = (int) yy_def[yy_current_state];
				if ( yy_current_state >= 310 )
					yy_c = yy_meta[yy_c];
				}
			yy_current_state = yy_nxt[yy_base[yy_current_state] + yy_c];
			++yy_cp;
			}
		while ( yy_base[yy_current_state] != 1367 );

yy_find_action:
		yy_act = yy_accept[yy_current_state];
		if ( yy_act == 0 )
			{ /* have to back up */
			yy_cp = (yy_last_accepting_cpos);
			yy_current_state = (yy_last_accepting_state);
			yy_act = yy_accept[yy_current_state];
			}

		YY_DO_BEFORE_ACTION;

do_action:	/* This label is used only to access EOF actions. */

		switch ( yy_act )
	{ /* beginning of action switch */
			case 0: /* must back up */
			/* undo the effects of YY_DO_BEFORE_ACTION */
			*yy_cp = (yy_hold_char);
			yy_cp = (yy_last_accepting_cpos);
			yy_current_state = (yy_last_accepting_state);
			goto yy_find_action;

case 1:
#line 42 "clexer.l"
case 2:
#line 43 "clexer.l"
case 3:
#line 44 "clexer.l"
case 4:
#line 45 "clexer.l"
case 5:
#line 46 "clexer.l"
case 6:
#line 47 "clexer.l"
case 7:
#line 48 "clexer.l"
case 8:
#line 49 "clexer.l"
case 9:
#line 50 "clexer.l"
case 10:
#line 51 "clexer.l"
case 11:
#line 52 "clexer.l"
case 12:
#line 53 "clexer.l"
case 13:
#line 54 "clexer.l"
case 14:
#line 55 "clexer.l"
case 15:
#line 56 "clexer.l"
case 16:
#line 57 "clexer.l"
case 17:
#line 58 "clexer.l"
case 18:
#line 59 "clexer.l"
case 19:
#line 60 "clexer.l"
case 20:
#line 61 "clexer.l"
case 21:
#line 62 "clexer.l"
case 22:
#line 63 "clexer.l"
case 23:
#line 64 "clexer.l"
case 24:
YY_RULE_SETUP
#line 64 "clexer.l"
{strcpy(yylval.value,yytext);return OP;}
	YY_BREAK
case 25:
YY_RULE_SETUP
#line 65 "clexer.l"
{strcpy(yylval.value,"ELLIPSIS");return OP;}
	YY_BREAK
case 26:
YY_RULE_SETUP
#line 66 "clexer.l"
{strcpy(yylval.value,"PLUSEQ");return OP;}
	YY_BREAK
case 27:
YY_RULE_SETUP
#line 67 "clexer.l"
{strcpy(yylval.value,"MINUSEQ");return OP;}
	YY_BREAK
case 28:
YY_RULE_SETUP
#line 68 "clexer.l"
{strcpy(yylval.value,"TIMESEQ");return OP;}
	YY_BREAK
case 29:
YY_RULE_SETUP
#line 69 "clexer.l"
{strcpy(yylval.value,"DIVEQ");return OP;}
	YY_BREAK
case 30:
YY_RULE_SETUP
#line 70 "clexer.l"
{strcpy(yylval.value,"MODEQ");return OP;}
	YY_BREAK
case 31:
YY_RULE_SETUP
#line 71 "clexer.l"
{strcpy(yylval.value,"SHLEQ");return OP;}
	YY_BREAK
case 32:
YY_RULE_SETUP
#line 72 "clexer.l"
{strcpy(yylval.value,"SHREQ");return OP;}
	YY_BREAK
case 33:
YY_RULE_SETUP
#line 73 "clexer.l"
{strcpy(yylval.value,"ANDEQ");return OP;}
	YY_BREAK
case 34:
YY_RULE_SETUP
#line 74 "clexer.l"
{strcpy(yylval.value,"XOREQ");return OP;}
	YY_BREAK
case 35:
YY_RULE_SETUP
#line 75 "clexer.l"
{strcpy(yylval.value,"OREQ");return OP;}
	YY_BREAK
case 36:
YY_RULE_SETUP
#line 76 "clexer.l"
{strcpy(yylval.value,"ARROW");return OP;}
	YY_BREAK
case 37:
YY_RULE_SETUP
#line 77 "clexer.l"
{strcpy(yylval.value,"PLUSPLUS");return OP;}
	YY_BREAK
case 38:
YY_RULE_SETUP
#line 78 "clexer.l"
{strcpy(yylval.value,"MINUSMINUS");return OP;}
	YY_BREAK
case 39:
YY_RULE_SETUP
#line 79 "clexer.l"
{strcpy(yylval.value,"SHL");return OP;}
	YY_BREAK
case 40:
YY_RULE_SETUP
#line 80 "clexer.l"
{strcpy(yylval.value,"SHR");return OP;}
	YY_BREAK
case 41:
YY_RULE_SETUP
#line 81 "clexer.l"
{strcpy(yylval.value,"LTEQ");return OP;}
	YY_BREAK
case 42:
YY_RULE_SETUP
#line 82 "clexer.l"
{strcpy(yylval.value,"GTEQ");return OP;}
	YY_BREAK
case 43:
YY_RULE_SETUP
#line 83 "clexer.l"
{strcpy(yylval.value,"EQEQ");return OP;}
	YY_BREAK
case 44:
YY_RULE_SETUP
#line 84 "clexer.l"
{strcpy(yylval.value,"NOTEQ");return OP;}
	YY_BREAK
case 45:
YY_RULE_SETUP
#line 85 "clexer.l"
{strcpy(yylval.value,"LOGAND");return OP;}
	YY_BREAK
case 46:
YY_RULE_SETUP
#line 86 "clexer.l"
{strcpy(yylval.value,"LOGOR");return OP;}
	YY_BREAK
case 47:
YY_RULE_SETUP
#line 87 "clexer.l"
{strcpy(yylval.value,"LTMOD");return OP;}
	YY_BREAK
case 48:
YY_RULE_SETUP
#line 88 "clexer.l"
{strcpy(yylval.value,"GTMOD");return OP;}
	YY_BREAK
case 49:
YY_RULE_SETUP
#line 89 "clexer.l"
{strcpy(yylval.value,"LTCOL");return OP;}
	YY_BREAK
case 50:
YY_RULE_SETUP
#line 90 "clexer.l"
{strcpy(yylval.value,"COLGT");return OP;}
	YY_BREAK
case 51:
YY_RULE_SETUP
#line 91 "clexer.l"
{strcpy(yylval.value,"MODCOL");return OP;}
	YY_BREAK
case 52:
YY_RULE_SETUP
#line 92 "clexer.l"
{strcpy(yylval.value,"MODCOLMOD");return OP;}
	YY_BREAK
case 53:
#line 94 "clexer.l"
case 54:
#line 95 "clexer.l"
case 55:
#line 96 "clexer.l"
case 56:
#line 97 "clexer.l"
case 57:
#line 98 "clexer.l"
case 58:
#line 99 "clexer.l"
case 59:
#line 100 "clexer.l"
case 60:
#line 101 "clexer.l"
case 61:
#line 102 "clexer.l"
case 62:
#line 103 "clexer.l"
case 63:
#line 104 "clexer.l"
case 64:
#line 105 "clexer.l"
case 65:
#line 106 "clexer.l"
case 66:
#line 107 "clexer.l"
case 67:
#line 108 "clexer.l"
case 68:
#line 109 "clexer.l"
case 69:
#line 110 "clexer.l"
case 70:
#line 111 "clexer.l"
case 71:
#line 112 "clexer.l"
case 72:
#line 113 "clexer.l"
case 73:
#line 114 "clexer.l"
case 74:
#line 115 "clexer.l"
case 75:
#line 116 "clexer.l"
case 76:
#line 117 "clexer.l"
case 77:
#line 118 "clexer.l"
case 78:
#line 119 "clexer.l"
case 79:
#line 120 "clexer.l"
case 80:
#line 121 "clexer.l"
case 81:
#line 122 "clexer.l"
case 82:
#line 123 "clexer.l"
case 83:
#line 124 "clexer.l"
case 84:
#line 125 "clexer.l"
case 85:
#line 126 "clexer.l"
case 86:
#line 127 "clexer.l"
case 87:
#line 128 "clexer.l"
case 88:
#line 129 "clexer.l"
case 89:
YY_RULE_SETUP
#line 129 "clexer.l"
{yylval.string_literal=yytext;return KEYWD;}
	YY_BREAK
case 90:
YY_RULE_SETUP
#line 130 "clexer.l"
{yylval.string_literal = string;pos=0;printf("%s %d CHARLIT ",file_name,line);BEGIN(CHRESC);}
	YY_BREAK
case 91:
YY_RULE_SETUP
#line 131 "clexer.l"
{yylval.string_literal = string;pos=0;printf("%s %d STRING ",file_name,line);BEGIN(STRESC);}
	YY_BREAK
case 92:
YY_RULE_SETUP
#line 132 "clexer.l"
{yylval.f=strtof(yytext,NULL);return FLOAT;}
	YY_BREAK
case 93:
YY_RULE_SETUP
#line 133 "clexer.l"
{yylval.d=strtod(yytext,NULL);return DOUBLE;}
	YY_BREAK
case 94:
YY_RULE_SETUP
#line 134 "clexer.l"
{yylval.d=strtod(yytext,NULL);return DOUBLE;}
	YY_BREAK
case 95:
YY_RULE_SETUP
#line 135 "clexer.l"
{yylval.integer=strtol(yytext,NULL,8);printf("%s %d NUMBER INTEGER %d INT\n",file_name,line,yylval.integer);return INT;}
	YY_BREAK
case 96:
YY_RULE_SETUP
#line 136 "clexer.l"
{yylval.integer=strtol(yytext,NULL,8);printf("%s %d NUMBER INTEGER %d UNSIGNED,INT\n",file_name,line,yylval.integer);return INT;}
	YY_BREAK
case 97:
YY_RULE_SETUP
#line 137 "clexer.l"
{yylval.integer=strtol(yytext,NULL,8);printf("%s %d NUMBER INTEGER %d LONG\n",file_name,line,yylval.integer);return INT;}
	YY_BREAK
case 98:
YY_RULE_SETUP
#line 138 "clexer.l"
{yylval.integer=strtol(yytext,NULL,8);printf("%s %d NUMBER INTEGER %d LONGLONG\n",file_name,line,yylval.integer);return INT;}
	YY_BREAK
case 99:
YY_RULE_SETUP
#line 139 "clexer.l"
{yylval.integer=strtol(yytext,NULL,8);printf("%s %d NUMBER INTEGER %d UNSIGNED,LONG\n",file_name,line,yylval.integer);return INT;}
	YY_BREAK
case 100:
YY_RULE_SETUP
#line 140 "clexer.l"
{yylval.integer=strtol(yytext,NULL,8);printf("%s %d NUMBER INTEGER %d UNSIGNED,LONGLONG\n",file_name,line,yylval.integer);return INT;}
	YY_BREAK
case 101:
YY_RULE_SETUP
#line 141 "clexer.l"
{yylval.integer=strtol(yytext,NULL,16);printf("%s %d NUMBER INTEGER %d INT\n",file_name,line,yylval.integer);return INT;}
	YY_BREAK
case 102:
YY_RULE_SETUP
#line 142 "clexer.l"
{yylval.integer=strtol(yytext,NULL,16);printf("%s %d NUMBER INTEGER %d UNSIGNED,INT\n",file_name,line,yylval.integer);return INT;}
	YY_BREAK
case 103:
YY_RULE_SETUP
#line 143 "clexer.l"
{yylval.integer=strtol(yytext,NULL,16);printf("%s %d NUMBER INTEGER %d LONG\n",file_name,line,yylval.integer);return INT;}
	YY_BREAK
case 104:
YY_RULE_SETUP
#line 144 "clexer.l"
{yylval.integer=strtol(yytext,NULL,16);printf("%s %d NUMBER INTEGER %d LONGLONG\n",file_name,line,yylval.integer);return INT;}
	YY_BREAK
case 105:
YY_RULE_SETUP
#line 145 "clexer.l"
{yylval.integer=strtol(yytext,NULL,16);printf("%s %d NUMBER INTEGER %d UNSIGNED,LONG\n",file_name,line,yylval.integer);return INT;}
	YY_BREAK
case 106:
YY_RULE_SETUP
#line 146 "clexer.l"
{yylval.integer=strtol(yytext,NULL,16);printf("%s %d NUMBER INTEGER %d UNSIGNED,LONGLONG\n",file_name,line,yylval.integer);return INT;}
	YY_BREAK
case 107:
YY_RULE_SETUP
#line 147 "clexer.l"
{yylval.integer=atoi(yytext);printf("%s %d NUMBER INTEGER %d INT\n",file_name,line,yylval.integer);return INT;}
	YY_BREAK
case 108:
YY_RULE_SETUP
#line 148 "clexer.l"
{yylval.integer=atoi(yytext);printf("%s %d NUMBER INTEGER %d UNSIGNED,INT\n",file_name,line,yylval.integer);return INT;}
	YY_BREAK
case 109:
YY_RULE_SETUP
#line 149 "clexer.l"
{yylval.integer=atoi(yytext);printf("%s %d NUMBER INTEGER %d LONG\n",file_name,line,yylval.integer);return INT;}
	YY_BREAK
case 110:
YY_RULE_SETUP
#line 150 "clexer.l"
{yylval.integer=atoi(yytext);printf("%s %d NUMBER INTEGER %d LONGLONG\n",file_name,line,yylval.integer);return INT;}
	YY_BREAK
case 111:
YY_RULE_SETUP
#line 151 "clexer.l"
{yylval.integer=atoi(yytext);printf("%s %d NUMBER INTEGER %d UNSIGNED,LONG\n",file_name,line,yylval.integer);return INT;}
	YY_BREAK
case 112:
YY_RULE_SETUP
#line 152 "clexer.l"
{yylval.integer=atoi(yytext);printf("%s %d NUMBER INTEGER %d UNSIGNED,LONGLONG\n",file_name,line,yylval.integer);return INT;}
	YY_BREAK
case 113:
YY_RULE_SETUP
#line 153 "clexer.l"
{yylval.string_literal=yytext;return IDENT;}
	YY_BREAK
case 114:
YY_RULE_SETUP
#line 154 "clexer.l"
{strcpy(yylval.value, yytext);return FILEN;}
	YY_BREAK
case 115:
YY_RULE_SETUP
#line 155 "clexer.l"

	YY_BREAK
case 116:
/* rule 116 can match eol */
YY_RULE_SETUP
#line 156 "clexer.l"
{line++;}
	YY_BREAK
case 117:
YY_RULE_SETUP
#line 157 "clexer.l"
{fprintf(stderr, "ERROR: unrecognized character `%s`\n",yytext);}
	YY_BREAK
case 118:
YY_RULE_SETUP
#line 160 "clexer.l"
{
			if(YYSTATE==STRESC || YYSTATE==CHRESC){
				yytext++;
				int val = strtol(yytext,NULL,8);
				if(val==0){
					yylval.string_literal[pos] = '\\';
					pos++;
					yylval.string_literal[pos] = '0';
					pos++;
				}else if(val>32 && val<128){
					yylval.string_literal[0] = val;
					pos++;
				}else if(val>255){
					yylval.string_literal[pos] = '\\';
					pos++;
					yylval.string_literal[pos] = '3';
					pos++;
					yylval.string_literal[pos] = '7';
					pos++;
					yylval.string_literal[pos] = '7';
					pos++;
				}else{
					yylval.string_literal[pos] = '\\';
					pos++;
					yylval.string_literal[pos+2] = 48 + val%8;
					val = val/8;
					yylval.string_literal[pos+1] = 48 + val%8;
					val = val/8;
					yylval.string_literal[pos] = 48 + val%8;
					pos = pos + 3;
				}
				if(YYSTATE==CHRESC){
					yylval.string_literal[pos] = '\0';
					printf("%c", yylval.string_literal[0]);
					BEGIN(ENDCHR);
				}
			}
			}
	YY_BREAK
case 119:
YY_RULE_SETUP
#line 198 "clexer.l"
{
		if(YYSTATE==STRESC || YYSTATE==CHRESC){
			yytext = yytext + 2;
			int val = strtol(yytext,NULL,16);
			if(val==0){
				yylval.string_literal[pos] = '\\';
				pos++;
				yylval.string_literal[pos] = '0';
				pos++;
			}else if(val>32 && val<128){
				yylval.string_literal[pos] = val;
				pos++;
			}else if(val>255){
				yylval.string_literal[pos] = '\\';
				pos++;
				yylval.string_literal[pos] = '3';
				pos++;
				yylval.string_literal[pos] = '7';
				pos++;
				yylval.string_literal[pos] = '7';
				pos++;
			}else{
				yylval.string_literal[pos] = '\\';
				pos++;
				yylval.string_literal[pos+2] = 48 + val%8;
				val = val/8;
				yylval.string_literal[pos+1] = 48 + val%8;
				val = val/8;
				yylval.string_literal[pos] = 48 + val%8;
				pos = pos + 3;
			}
			if(YYSTATE==CHRESC){
				yylval.string_literal[pos] = '\0';
				printf("%s", yylval.string_literal);
				BEGIN(ENDCHR);
			}
		}
		}
	YY_BREAK
case 120:
YY_RULE_SETUP
#line 236 "clexer.l"
{
			if(YYSTATE==STRESC || YYSTATE==CHRESC){
				char *ch = yytext;
				ch++;
				if(*ch == '0' || *ch == 'a' || *ch=='b' || *ch=='f' || *ch=='n' || *ch == 'r'|| *ch=='t' || *ch=='v' || *ch=='\'' || *ch == '\\' || *ch=='\"'){
					yylval.string_literal[pos] = '\\';
					pos++;
					yylval.string_literal[pos] = *ch;
					pos++;
				}else{
					yylval.string_literal[pos] = *ch;
					pos++;
				}
				if(YYSTATE==CHRESC){
					yylval.string_literal[pos] = '\0';
					printf("%s",yylval.string_literal);
					BEGIN(ENDCHR);
				}
			}
			}
	YY_BREAK
case 121:
YY_RULE_SETUP
#line 258 "clexer.l"
{
		yylval.string_literal[pos] = '\0';
		printf("%s ", yylval.string_literal);
		printf(" \n ");
		return STRING;
		}
	YY_BREAK
case 122:
YY_RULE_SETUP
#line 265 "clexer.l"
{
		printf("\n");
		return CHAR;
		}
	YY_BREAK
case 123:
/* rule 123 can match eol */
YY_RULE_SETUP
#line 269 "clexer.l"
{printf(" \n");line++;}
	YY_BREAK
case 124:
YY_RULE_SETUP
#line 270 "clexer.l"
{
	   if(YYSTATE==STRESC || YYSTATE==CHRESC) {
		yylval.string_literal[pos]= *yytext;
		pos++;
	 	if(YYSTATE==CHRESC){
			yylval.string_literal[pos] = '\0';
			printf("%s",yylval.string_literal);
			BEGIN(ENDCHR);
		}
	 }
	 }
	YY_BREAK
case 125:
YY_RULE_SETUP
#line 283 "clexer.l"

	YY_BREAK
case 126:
YY_RULE_SETUP
#line 285 "clexer.l"
ECHO;
	YY_BREAK
#line 1741 "lex.yy.c"
case YY_STATE_EOF(INITIAL):
case YY_STATE_EOF(STRESC):
case YY_STATE_EOF(CHRESC):
case YY_STATE_EOF(SIGN):
case YY_STATE_EOF(ENDCHR):
	yyterminate();

	case YY_END_OF_BUFFER:
		{
		/* Amount of text matched not including the EOB char. */
		int yy_amount_of_matched_text = (int) (yy_cp - (yytext_ptr)) - 1;

		/* Undo the effects of YY_DO_BEFORE_ACTION. */
		*yy_cp = (yy_hold_char);
		YY_RESTORE_YY_MORE_OFFSET

		if ( YY_CURRENT_BUFFER_LVALUE->yy_buffer_status == YY_BUFFER_NEW )
			{
			/* We're scanning a new file or input source.  It's
			 * possible that this happened because the user
			 * just pointed yyin at a new source and called
			 * yylex().  If so, then we have to assure
			 * consistency between YY_CURRENT_BUFFER and our
			 * globals.  Here is the right place to do so, because
			 * this is the first action (other than possibly a
			 * back-up) that will match for the new input source.
			 */
			(yy_n_chars) = YY_CURRENT_BUFFER_LVALUE->yy_n_chars;
			YY_CURRENT_BUFFER_LVALUE->yy_input_file = yyin;
			YY_CURRENT_BUFFER_LVALUE->yy_buffer_status = YY_BUFFER_NORMAL;
			}

		/* Note that here we test for yy_c_buf_p "<=" to the position
		 * of the first EOB in the buffer, since yy_c_buf_p will
		 * already have been incremented past the NUL character
		 * (since all states make transitions on EOB to the
		 * end-of-buffer state).  Contrast this with the test
		 * in input().
		 */
		if ( (yy_c_buf_p) <= &YY_CURRENT_BUFFER_LVALUE->yy_ch_buf[(yy_n_chars)] )
			{ /* This was really a NUL. */
			yy_state_type yy_next_state;

			(yy_c_buf_p) = (yytext_ptr) + yy_amount_of_matched_text;

			yy_current_state = yy_get_previous_state(  );

			/* Okay, we're now positioned to make the NUL
			 * transition.  We couldn't have
			 * yy_get_previous_state() go ahead and do it
			 * for us because it doesn't know how to deal
			 * with the possibility of jamming (and we don't
			 * want to build jamming into it because then it
			 * will run more slowly).
			 */

			yy_next_state = yy_try_NUL_trans( yy_current_state );

			yy_bp = (yytext_ptr) + YY_MORE_ADJ;

			if ( yy_next_state )
				{
				/* Consume the NUL. */
				yy_cp = ++(yy_c_buf_p);
				yy_current_state = yy_next_state;
				goto yy_match;
				}

			else
				{
				yy_cp = (yy_c_buf_p);
				goto yy_find_action;
				}
			}

		else switch ( yy_get_next_buffer(  ) )
			{
			case EOB_ACT_END_OF_FILE:
				{
				(yy_did_buffer_switch_on_eof) = 0;

				if ( yywrap(  ) )
					{
					/* Note: because we've taken care in
					 * yy_get_next_buffer() to have set up
					 * yytext, we can now set up
					 * yy_c_buf_p so that if some total
					 * hoser (like flex itself) wants to
					 * call the scanner after we return the
					 * YY_NULL, it'll still work - another
					 * YY_NULL will get returned.
					 */
					(yy_c_buf_p) = (yytext_ptr) + YY_MORE_ADJ;

					yy_act = YY_STATE_EOF(YY_START);
					goto do_action;
					}

				else
					{
					if ( ! (yy_did_buffer_switch_on_eof) )
						YY_NEW_FILE;
					}
				break;
				}

			case EOB_ACT_CONTINUE_SCAN:
				(yy_c_buf_p) =
					(yytext_ptr) + yy_amount_of_matched_text;

				yy_current_state = yy_get_previous_state(  );

				yy_cp = (yy_c_buf_p);
				yy_bp = (yytext_ptr) + YY_MORE_ADJ;
				goto yy_match;

			case EOB_ACT_LAST_MATCH:
				(yy_c_buf_p) =
				&YY_CURRENT_BUFFER_LVALUE->yy_ch_buf[(yy_n_chars)];

				yy_current_state = yy_get_previous_state(  );

				yy_cp = (yy_c_buf_p);
				yy_bp = (yytext_ptr) + YY_MORE_ADJ;
				goto yy_find_action;
			}
		break;
		}

	default:
		YY_FATAL_ERROR(
			"fatal flex scanner internal error--no action found" );
	} /* end of action switch */
		} /* end of scanning one token */
	} /* end of user's declarations */
} /* end of yylex */

/* yy_get_next_buffer - try to read in a new buffer
 *
 * Returns a code representing an action:
 *	EOB_ACT_LAST_MATCH -
 *	EOB_ACT_CONTINUE_SCAN - continue scanning from current position
 *	EOB_ACT_END_OF_FILE - end of file
 */
static int yy_get_next_buffer (void)
{
    	char *dest = YY_CURRENT_BUFFER_LVALUE->yy_ch_buf;
	char *source = (yytext_ptr);
	int number_to_move, i;
	int ret_val;

	if ( (yy_c_buf_p) > &YY_CURRENT_BUFFER_LVALUE->yy_ch_buf[(yy_n_chars) + 1] )
		YY_FATAL_ERROR(
		"fatal flex scanner internal error--end of buffer missed" );

	if ( YY_CURRENT_BUFFER_LVALUE->yy_fill_buffer == 0 )
		{ /* Don't try to fill the buffer, so this is an EOF. */
		if ( (yy_c_buf_p) - (yytext_ptr) - YY_MORE_ADJ == 1 )
			{
			/* We matched a single character, the EOB, so
			 * treat this as a final EOF.
			 */
			return EOB_ACT_END_OF_FILE;
			}

		else
			{
			/* We matched some text prior to the EOB, first
			 * process it.
			 */
			return EOB_ACT_LAST_MATCH;
			}
		}

	/* Try to read more data. */

	/* First move last chars to start of buffer. */
	number_to_move = (int) ((yy_c_buf_p) - (yytext_ptr) - 1);

	for ( i = 0; i < number_to_move; ++i )
		*(dest++) = *(source++);

	if ( YY_CURRENT_BUFFER_LVALUE->yy_buffer_status == YY_BUFFER_EOF_PENDING )
		/* don't do the read, it's not guaranteed to return an EOF,
		 * just force an EOF
		 */
		YY_CURRENT_BUFFER_LVALUE->yy_n_chars = (yy_n_chars) = 0;

	else
		{
			int num_to_read =
			YY_CURRENT_BUFFER_LVALUE->yy_buf_size - number_to_move - 1;

		while ( num_to_read <= 0 )
			{ /* Not enough room in the buffer - grow it. */

			/* just a shorter name for the current buffer */
			YY_BUFFER_STATE b = YY_CURRENT_BUFFER_LVALUE;

			int yy_c_buf_p_offset =
				(int) ((yy_c_buf_p) - b->yy_ch_buf);

			if ( b->yy_is_our_buffer )
				{
				int new_size = b->yy_buf_size * 2;

				if ( new_size <= 0 )
					b->yy_buf_size += b->yy_buf_size / 8;
				else
					b->yy_buf_size *= 2;

				b->yy_ch_buf = (char *)
					/* Include room in for 2 EOB chars. */
					yyrealloc( (void *) b->yy_ch_buf,
							 (yy_size_t) (b->yy_buf_size + 2)  );
				}
			else
				/* Can't grow it, we don't own it. */
				b->yy_ch_buf = NULL;

			if ( ! b->yy_ch_buf )
				YY_FATAL_ERROR(
				"fatal error - scanner input buffer overflow" );

			(yy_c_buf_p) = &b->yy_ch_buf[yy_c_buf_p_offset];

			num_to_read = YY_CURRENT_BUFFER_LVALUE->yy_buf_size -
						number_to_move - 1;

			}

		if ( num_to_read > YY_READ_BUF_SIZE )
			num_to_read = YY_READ_BUF_SIZE;

		/* Read in more data. */
		YY_INPUT( (&YY_CURRENT_BUFFER_LVALUE->yy_ch_buf[number_to_move]),
			(yy_n_chars), num_to_read );

		YY_CURRENT_BUFFER_LVALUE->yy_n_chars = (yy_n_chars);
		}

	if ( (yy_n_chars) == 0 )
		{
		if ( number_to_move == YY_MORE_ADJ )
			{
			ret_val = EOB_ACT_END_OF_FILE;
			yyrestart( yyin  );
			}

		else
			{
			ret_val = EOB_ACT_LAST_MATCH;
			YY_CURRENT_BUFFER_LVALUE->yy_buffer_status =
				YY_BUFFER_EOF_PENDING;
			}
		}

	else
		ret_val = EOB_ACT_CONTINUE_SCAN;

	if (((yy_n_chars) + number_to_move) > YY_CURRENT_BUFFER_LVALUE->yy_buf_size) {
		/* Extend the array by 50%, plus the number we really need. */
		int new_size = (yy_n_chars) + number_to_move + ((yy_n_chars) >> 1);
		YY_CURRENT_BUFFER_LVALUE->yy_ch_buf = (char *) yyrealloc(
			(void *) YY_CURRENT_BUFFER_LVALUE->yy_ch_buf, (yy_size_t) new_size  );
		if ( ! YY_CURRENT_BUFFER_LVALUE->yy_ch_buf )
			YY_FATAL_ERROR( "out of dynamic memory in yy_get_next_buffer()" );
		/* "- 2" to take care of EOB's */
		YY_CURRENT_BUFFER_LVALUE->yy_buf_size = (int) (new_size - 2);
	}

	(yy_n_chars) += number_to_move;
	YY_CURRENT_BUFFER_LVALUE->yy_ch_buf[(yy_n_chars)] = YY_END_OF_BUFFER_CHAR;
	YY_CURRENT_BUFFER_LVALUE->yy_ch_buf[(yy_n_chars) + 1] = YY_END_OF_BUFFER_CHAR;

	(yytext_ptr) = &YY_CURRENT_BUFFER_LVALUE->yy_ch_buf[0];

	return ret_val;
}

/* yy_get_previous_state - get the state just before the EOB char was reached */

    static yy_state_type yy_get_previous_state (void)
{
	yy_state_type yy_current_state;
	char *yy_cp;
    
	yy_current_state = (yy_start);

	for ( yy_cp = (yytext_ptr) + YY_MORE_ADJ; yy_cp < (yy_c_buf_p); ++yy_cp )
		{
		YY_CHAR yy_c = (*yy_cp ? yy_ec[YY_SC_TO_UI(*yy_cp)] : 1);
		if ( yy_accept[yy_current_state] )
			{
			(yy_last_accepting_state) = yy_current_state;
			(yy_last_accepting_cpos) = yy_cp;
			}
		while ( yy_chk[yy_base[yy_current_state] + yy_c] != yy_current_state )
			{
			yy_current_state = (int) yy_def[yy_current_state];
			if ( yy_current_state >= 310 )
				yy_c = yy_meta[yy_c];
			}
		yy_current_state = yy_nxt[yy_base[yy_current_state] + yy_c];
		}

	return yy_current_state;
}

/* yy_try_NUL_trans - try to make a transition on the NUL character
 *
 * synopsis
 *	next_state = yy_try_NUL_trans( current_state );
 */
    static yy_state_type yy_try_NUL_trans  (yy_state_type yy_current_state )
{
	int yy_is_jam;
    	char *yy_cp = (yy_c_buf_p);

	YY_CHAR yy_c = 1;
	if ( yy_accept[yy_current_state] )
		{
		(yy_last_accepting_state) = yy_current_state;
		(yy_last_accepting_cpos) = yy_cp;
		}
	while ( yy_chk[yy_base[yy_current_state] + yy_c] != yy_current_state )
		{
		yy_current_state = (int) yy_def[yy_current_state];
		if ( yy_current_state >= 310 )
			yy_c = yy_meta[yy_c];
		}
	yy_current_state = yy_nxt[yy_base[yy_current_state] + yy_c];
	yy_is_jam = (yy_current_state == 309);

		return yy_is_jam ? 0 : yy_current_state;
}

#ifndef YY_NO_UNPUT

    static void yyunput (int c, char * yy_bp )
{
	char *yy_cp;
    
    yy_cp = (yy_c_buf_p);

	/* undo effects of setting up yytext */
	*yy_cp = (yy_hold_char);

	if ( yy_cp < YY_CURRENT_BUFFER_LVALUE->yy_ch_buf + 2 )
		{ /* need to shift things up to make room */
		/* +2 for EOB chars. */
		int number_to_move = (yy_n_chars) + 2;
		char *dest = &YY_CURRENT_BUFFER_LVALUE->yy_ch_buf[
					YY_CURRENT_BUFFER_LVALUE->yy_buf_size + 2];
		char *source =
				&YY_CURRENT_BUFFER_LVALUE->yy_ch_buf[number_to_move];

		while ( source > YY_CURRENT_BUFFER_LVALUE->yy_ch_buf )
			*--dest = *--source;

		yy_cp += (int) (dest - source);
		yy_bp += (int) (dest - source);
		YY_CURRENT_BUFFER_LVALUE->yy_n_chars =
			(yy_n_chars) = (int) YY_CURRENT_BUFFER_LVALUE->yy_buf_size;

		if ( yy_cp < YY_CURRENT_BUFFER_LVALUE->yy_ch_buf + 2 )
			YY_FATAL_ERROR( "flex scanner push-back overflow" );
		}

	*--yy_cp = (char) c;

	(yytext_ptr) = yy_bp;
	(yy_hold_char) = *yy_cp;
	(yy_c_buf_p) = yy_cp;
}

#endif

#ifndef YY_NO_INPUT
#ifdef __cplusplus
    static int yyinput (void)
#else
    static int input  (void)
#endif

{
	int c;
    
	*(yy_c_buf_p) = (yy_hold_char);

	if ( *(yy_c_buf_p) == YY_END_OF_BUFFER_CHAR )
		{
		/* yy_c_buf_p now points to the character we want to return.
		 * If this occurs *before* the EOB characters, then it's a
		 * valid NUL; if not, then we've hit the end of the buffer.
		 */
		if ( (yy_c_buf_p) < &YY_CURRENT_BUFFER_LVALUE->yy_ch_buf[(yy_n_chars)] )
			/* This was really a NUL. */
			*(yy_c_buf_p) = '\0';

		else
			{ /* need more input */
			int offset = (int) ((yy_c_buf_p) - (yytext_ptr));
			++(yy_c_buf_p);

			switch ( yy_get_next_buffer(  ) )
				{
				case EOB_ACT_LAST_MATCH:
					/* This happens because yy_g_n_b()
					 * sees that we've accumulated a
					 * token and flags that we need to
					 * try matching the token before
					 * proceeding.  But for input(),
					 * there's no matching to consider.
					 * So convert the EOB_ACT_LAST_MATCH
					 * to EOB_ACT_END_OF_FILE.
					 */

					/* Reset buffer status. */
					yyrestart( yyin );

					/*FALLTHROUGH*/

				case EOB_ACT_END_OF_FILE:
					{
					if ( yywrap(  ) )
						return 0;

					if ( ! (yy_did_buffer_switch_on_eof) )
						YY_NEW_FILE;
#ifdef __cplusplus
					return yyinput();
#else
					return input();
#endif
					}

				case EOB_ACT_CONTINUE_SCAN:
					(yy_c_buf_p) = (yytext_ptr) + offset;
					break;
				}
			}
		}

	c = *(unsigned char *) (yy_c_buf_p);	/* cast for 8-bit char's */
	*(yy_c_buf_p) = '\0';	/* preserve yytext */
	(yy_hold_char) = *++(yy_c_buf_p);

	return c;
}
#endif	/* ifndef YY_NO_INPUT */

/** Immediately switch to a different input stream.
 * @param input_file A readable stream.
 * 
 * @note This function does not reset the start condition to @c INITIAL .
 */
    void yyrestart  (FILE * input_file )
{
    
	if ( ! YY_CURRENT_BUFFER ){
        yyensure_buffer_stack ();
		YY_CURRENT_BUFFER_LVALUE =
            yy_create_buffer( yyin, YY_BUF_SIZE );
	}

	yy_init_buffer( YY_CURRENT_BUFFER, input_file );
	yy_load_buffer_state(  );
}

/** Switch to a different input buffer.
 * @param new_buffer The new input buffer.
 * 
 */
    void yy_switch_to_buffer  (YY_BUFFER_STATE  new_buffer )
{
    
	/* TODO. We should be able to replace this entire function body
	 * with
	 *		yypop_buffer_state();
	 *		yypush_buffer_state(new_buffer);
     */
	yyensure_buffer_stack ();
	if ( YY_CURRENT_BUFFER == new_buffer )
		return;

	if ( YY_CURRENT_BUFFER )
		{
		/* Flush out information for old buffer. */
		*(yy_c_buf_p) = (yy_hold_char);
		YY_CURRENT_BUFFER_LVALUE->yy_buf_pos = (yy_c_buf_p);
		YY_CURRENT_BUFFER_LVALUE->yy_n_chars = (yy_n_chars);
		}

	YY_CURRENT_BUFFER_LVALUE = new_buffer;
	yy_load_buffer_state(  );

	/* We don't actually know whether we did this switch during
	 * EOF (yywrap()) processing, but the only time this flag
	 * is looked at is after yywrap() is called, so it's safe
	 * to go ahead and always set it.
	 */
	(yy_did_buffer_switch_on_eof) = 1;
}

static void yy_load_buffer_state  (void)
{
    	(yy_n_chars) = YY_CURRENT_BUFFER_LVALUE->yy_n_chars;
	(yytext_ptr) = (yy_c_buf_p) = YY_CURRENT_BUFFER_LVALUE->yy_buf_pos;
	yyin = YY_CURRENT_BUFFER_LVALUE->yy_input_file;
	(yy_hold_char) = *(yy_c_buf_p);
}

/** Allocate and initialize an input buffer state.
 * @param file A readable stream.
 * @param size The character buffer size in bytes. When in doubt, use @c YY_BUF_SIZE.
 * 
 * @return the allocated buffer state.
 */
    YY_BUFFER_STATE yy_create_buffer  (FILE * file, int  size )
{
	YY_BUFFER_STATE b;
    
	b = (YY_BUFFER_STATE) yyalloc( sizeof( struct yy_buffer_state )  );
	if ( ! b )
		YY_FATAL_ERROR( "out of dynamic memory in yy_create_buffer()" );

	b->yy_buf_size = size;

	/* yy_ch_buf has to be 2 characters longer than the size given because
	 * we need to put in 2 end-of-buffer characters.
	 */
	b->yy_ch_buf = (char *) yyalloc( (yy_size_t) (b->yy_buf_size + 2)  );
	if ( ! b->yy_ch_buf )
		YY_FATAL_ERROR( "out of dynamic memory in yy_create_buffer()" );

	b->yy_is_our_buffer = 1;

	yy_init_buffer( b, file );

	return b;
}

/** Destroy the buffer.
 * @param b a buffer created with yy_create_buffer()
 * 
 */
    void yy_delete_buffer (YY_BUFFER_STATE  b )
{
    
	if ( ! b )
		return;

	if ( b == YY_CURRENT_BUFFER ) /* Not sure if we should pop here. */
		YY_CURRENT_BUFFER_LVALUE = (YY_BUFFER_STATE) 0;

	if ( b->yy_is_our_buffer )
		yyfree( (void *) b->yy_ch_buf  );

	yyfree( (void *) b  );
}

/* Initializes or reinitializes a buffer.
 * This function is sometimes called more than once on the same buffer,
 * such as during a yyrestart() or at EOF.
 */
    static void yy_init_buffer  (YY_BUFFER_STATE  b, FILE * file )

{
	int oerrno = errno;
    
	yy_flush_buffer( b );

	b->yy_input_file = file;
	b->yy_fill_buffer = 1;

    /* If b is the current buffer, then yy_init_buffer was _probably_
     * called from yyrestart() or through yy_get_next_buffer.
     * In that case, we don't want to reset the lineno or column.
     */
    if (b != YY_CURRENT_BUFFER){
        b->yy_bs_lineno = 1;
        b->yy_bs_column = 0;
    }

        b->yy_is_interactive = file ? (isatty( fileno(file) ) > 0) : 0;
    
	errno = oerrno;
}

/** Discard all buffered characters. On the next scan, YY_INPUT will be called.
 * @param b the buffer state to be flushed, usually @c YY_CURRENT_BUFFER.
 * 
 */
    void yy_flush_buffer (YY_BUFFER_STATE  b )
{
    	if ( ! b )
		return;

	b->yy_n_chars = 0;

	/* We always need two end-of-buffer characters.  The first causes
	 * a transition to the end-of-buffer state.  The second causes
	 * a jam in that state.
	 */
	b->yy_ch_buf[0] = YY_END_OF_BUFFER_CHAR;
	b->yy_ch_buf[1] = YY_END_OF_BUFFER_CHAR;

	b->yy_buf_pos = &b->yy_ch_buf[0];

	b->yy_at_bol = 1;
	b->yy_buffer_status = YY_BUFFER_NEW;

	if ( b == YY_CURRENT_BUFFER )
		yy_load_buffer_state(  );
}

/** Pushes the new state onto the stack. The new state becomes
 *  the current state. This function will allocate the stack
 *  if necessary.
 *  @param new_buffer The new state.
 *  
 */
void yypush_buffer_state (YY_BUFFER_STATE new_buffer )
{
    	if (new_buffer == NULL)
		return;

	yyensure_buffer_stack();

	/* This block is copied from yy_switch_to_buffer. */
	if ( YY_CURRENT_BUFFER )
		{
		/* Flush out information for old buffer. */
		*(yy_c_buf_p) = (yy_hold_char);
		YY_CURRENT_BUFFER_LVALUE->yy_buf_pos = (yy_c_buf_p);
		YY_CURRENT_BUFFER_LVALUE->yy_n_chars = (yy_n_chars);
		}

	/* Only push if top exists. Otherwise, replace top. */
	if (YY_CURRENT_BUFFER)
		(yy_buffer_stack_top)++;
	YY_CURRENT_BUFFER_LVALUE = new_buffer;

	/* copied from yy_switch_to_buffer. */
	yy_load_buffer_state(  );
	(yy_did_buffer_switch_on_eof) = 1;
}

/** Removes and deletes the top of the stack, if present.
 *  The next element becomes the new top.
 *  
 */
void yypop_buffer_state (void)
{
    	if (!YY_CURRENT_BUFFER)
		return;

	yy_delete_buffer(YY_CURRENT_BUFFER );
	YY_CURRENT_BUFFER_LVALUE = NULL;
	if ((yy_buffer_stack_top) > 0)
		--(yy_buffer_stack_top);

	if (YY_CURRENT_BUFFER) {
		yy_load_buffer_state(  );
		(yy_did_buffer_switch_on_eof) = 1;
	}
}

/* Allocates the stack if it does not exist.
 *  Guarantees space for at least one push.
 */
static void yyensure_buffer_stack (void)
{
	yy_size_t num_to_alloc;
    
	if (!(yy_buffer_stack)) {

		/* First allocation is just for 2 elements, since we don't know if this
		 * scanner will even need a stack. We use 2 instead of 1 to avoid an
		 * immediate realloc on the next call.
         */
      num_to_alloc = 1; /* After all that talk, this was set to 1 anyways... */
		(yy_buffer_stack) = (struct yy_buffer_state**)yyalloc
								(num_to_alloc * sizeof(struct yy_buffer_state*)
								);
		if ( ! (yy_buffer_stack) )
			YY_FATAL_ERROR( "out of dynamic memory in yyensure_buffer_stack()" );

		memset((yy_buffer_stack), 0, num_to_alloc * sizeof(struct yy_buffer_state*));

		(yy_buffer_stack_max) = num_to_alloc;
		(yy_buffer_stack_top) = 0;
		return;
	}

	if ((yy_buffer_stack_top) >= ((yy_buffer_stack_max)) - 1){

		/* Increase the buffer to prepare for a possible push. */
		yy_size_t grow_size = 8 /* arbitrary grow size */;

		num_to_alloc = (yy_buffer_stack_max) + grow_size;
		(yy_buffer_stack) = (struct yy_buffer_state**)yyrealloc
								((yy_buffer_stack),
								num_to_alloc * sizeof(struct yy_buffer_state*)
								);
		if ( ! (yy_buffer_stack) )
			YY_FATAL_ERROR( "out of dynamic memory in yyensure_buffer_stack()" );

		/* zero only the new slots.*/
		memset((yy_buffer_stack) + (yy_buffer_stack_max), 0, grow_size * sizeof(struct yy_buffer_state*));
		(yy_buffer_stack_max) = num_to_alloc;
	}
}

/** Setup the input buffer state to scan directly from a user-specified character buffer.
 * @param base the character buffer
 * @param size the size in bytes of the character buffer
 * 
 * @return the newly allocated buffer state object.
 */
YY_BUFFER_STATE yy_scan_buffer  (char * base, yy_size_t  size )
{
	YY_BUFFER_STATE b;
    
	if ( size < 2 ||
	     base[size-2] != YY_END_OF_BUFFER_CHAR ||
	     base[size-1] != YY_END_OF_BUFFER_CHAR )
		/* They forgot to leave room for the EOB's. */
		return NULL;

	b = (YY_BUFFER_STATE) yyalloc( sizeof( struct yy_buffer_state )  );
	if ( ! b )
		YY_FATAL_ERROR( "out of dynamic memory in yy_scan_buffer()" );

	b->yy_buf_size = (int) (size - 2);	/* "- 2" to take care of EOB's */
	b->yy_buf_pos = b->yy_ch_buf = base;
	b->yy_is_our_buffer = 0;
	b->yy_input_file = NULL;
	b->yy_n_chars = b->yy_buf_size;
	b->yy_is_interactive = 0;
	b->yy_at_bol = 1;
	b->yy_fill_buffer = 0;
	b->yy_buffer_status = YY_BUFFER_NEW;

	yy_switch_to_buffer( b  );

	return b;
}

/** Setup the input buffer state to scan a string. The next call to yylex() will
 * scan from a @e copy of @a str.
 * @param yystr a NUL-terminated string to scan
 * 
 * @return the newly allocated buffer state object.
 * @note If you want to scan bytes that may contain NUL values, then use
 *       yy_scan_bytes() instead.
 */
YY_BUFFER_STATE yy_scan_string (const char * yystr )
{
    
	return yy_scan_bytes( yystr, (int) strlen(yystr) );
}

/** Setup the input buffer state to scan the given bytes. The next call to yylex() will
 * scan from a @e copy of @a bytes.
 * @param yybytes the byte buffer to scan
 * @param _yybytes_len the number of bytes in the buffer pointed to by @a bytes.
 * 
 * @return the newly allocated buffer state object.
 */
YY_BUFFER_STATE yy_scan_bytes  (const char * yybytes, int  _yybytes_len )
{
	YY_BUFFER_STATE b;
	char *buf;
	yy_size_t n;
	int i;
    
	/* Get memory for full buffer, including space for trailing EOB's. */
	n = (yy_size_t) (_yybytes_len + 2);
	buf = (char *) yyalloc( n  );
	if ( ! buf )
		YY_FATAL_ERROR( "out of dynamic memory in yy_scan_bytes()" );

	for ( i = 0; i < _yybytes_len; ++i )
		buf[i] = yybytes[i];

	buf[_yybytes_len] = buf[_yybytes_len+1] = YY_END_OF_BUFFER_CHAR;

	b = yy_scan_buffer( buf, n );
	if ( ! b )
		YY_FATAL_ERROR( "bad buffer in yy_scan_bytes()" );

	/* It's okay to grow etc. this buffer, and we should throw it
	 * away when we're done.
	 */
	b->yy_is_our_buffer = 1;

	return b;
}

#ifndef YY_EXIT_FAILURE
#define YY_EXIT_FAILURE 2
#endif

static void yynoreturn yy_fatal_error (const char* msg )
{
			fprintf( stderr, "%s\n", msg );
	exit( YY_EXIT_FAILURE );
}

/* Redefine yyless() so it works in section 3 code. */

#undef yyless
#define yyless(n) \
	do \
		{ \
		/* Undo effects of setting up yytext. */ \
        int yyless_macro_arg = (n); \
        YY_LESS_LINENO(yyless_macro_arg);\
		yytext[yyleng] = (yy_hold_char); \
		(yy_c_buf_p) = yytext + yyless_macro_arg; \
		(yy_hold_char) = *(yy_c_buf_p); \
		*(yy_c_buf_p) = '\0'; \
		yyleng = yyless_macro_arg; \
		} \
	while ( 0 )

/* Accessor  methods (get/set functions) to struct members. */

/** Get the current line number.
 * 
 */
int yyget_lineno  (void)
{
    
    return yylineno;
}

/** Get the input stream.
 * 
 */
FILE *yyget_in  (void)
{
        return yyin;
}

/** Get the output stream.
 * 
 */
FILE *yyget_out  (void)
{
        return yyout;
}

/** Get the length of the current token.
 * 
 */
int yyget_leng  (void)
{
        return yyleng;
}

/** Get the current token.
 * 
 */

char *yyget_text  (void)
{
        return yytext;
}

/** Set the current line number.
 * @param _line_number line number
 * 
 */
void yyset_lineno (int  _line_number )
{
    
    yylineno = _line_number;
}

/** Set the input stream. This does not discard the current
 * input buffer.
 * @param _in_str A readable stream.
 * 
 * @see yy_switch_to_buffer
 */
void yyset_in (FILE *  _in_str )
{
        yyin = _in_str ;
}

void yyset_out (FILE *  _out_str )
{
        yyout = _out_str ;
}

int yyget_debug  (void)
{
        return yy_flex_debug;
}

void yyset_debug (int  _bdebug )
{
        yy_flex_debug = _bdebug ;
}

static int yy_init_globals (void)
{
        /* Initialization is the same as for the non-reentrant scanner.
     * This function is called from yylex_destroy(), so don't allocate here.
     */

    (yy_buffer_stack) = NULL;
    (yy_buffer_stack_top) = 0;
    (yy_buffer_stack_max) = 0;
    (yy_c_buf_p) = NULL;
    (yy_init) = 0;
    (yy_start) = 0;

/* Defined in main.c */
#ifdef YY_STDINIT
    yyin = stdin;
    yyout = stdout;
#else
    yyin = NULL;
    yyout = NULL;
#endif

    /* For future reference: Set errno on error, since we are called by
     * yylex_init()
     */
    return 0;
}

/* yylex_destroy is for both reentrant and non-reentrant scanners. */
int yylex_destroy  (void)
{
    
    /* Pop the buffer stack, destroying each element. */
	while(YY_CURRENT_BUFFER){
		yy_delete_buffer( YY_CURRENT_BUFFER  );
		YY_CURRENT_BUFFER_LVALUE = NULL;
		yypop_buffer_state();
	}

	/* Destroy the stack itself. */
	yyfree((yy_buffer_stack) );
	(yy_buffer_stack) = NULL;

    /* Reset the globals. This is important in a non-reentrant scanner so the next time
     * yylex() is called, initialization will occur. */
    yy_init_globals( );

    return 0;
}

/*
 * Internal utility routines.
 */

#ifndef yytext_ptr
static void yy_flex_strncpy (char* s1, const char * s2, int n )
{
		
	int i;
	for ( i = 0; i < n; ++i )
		s1[i] = s2[i];
}
#endif

#ifdef YY_NEED_STRLEN
static int yy_flex_strlen (const char * s )
{
	int n;
	for ( n = 0; s[n]; ++n )
		;

	return n;
}
#endif

void *yyalloc (yy_size_t  size )
{
			return malloc(size);
}

void *yyrealloc  (void * ptr, yy_size_t  size )
{
		
	/* The cast to (char *) in the following accommodates both
	 * implementations that use char* generic pointers, and those
	 * that use void* generic pointers.  It works with the latter
	 * because both ANSI C and C++ allow castless assignment from
	 * any pointer type to void*, and deal with argument conversions
	 * as though doing an assignment.
	 */
	return realloc(ptr, size);
}

void yyfree (void * ptr )
{
			free( (char *) ptr );	/* see yyrealloc() for (char *) cast */
}

#define YYTABLES_NAME "yytables"

#line 285 "clexer.l"


main()
{
 int t;
 char *cptr;
 char c[4];
 char b;
	while (t=yylex())
	{
	 switch(t)
	 {
		case OP:
			printf("%s %d %s\n",file_name,line,yylval.value);
			break;
		case FILEN:
			cptr = strtok(yylval.value,"\"");
	 		cptr = strtok(NULL,"\"");
			line = 0;
			strcpy(file_name, cptr);
			break;
	 	case IDENT:
			printf("%s %d IDENT %s\n",file_name,line,yylval.string_literal);
			break;
		case KEYWD:
			cptr = yylval.string_literal;
			while(*cptr){
				*cptr = toupper((unsigned char) *cptr);
				cptr++;
			}
			printf("%s %d %s\n",file_name,line,yylval.string_literal);
			break;
		case FLOAT:
		        printf("%s %d NUMBER REAL %.e FLOAT\n",file_name,line,yylval.f);
			break;
		case DOUBLE:
			printf("%s %d NUMBER REAL %f DOUBLE\n",file_name,line,yylval.d);
		case STRING:
			BEGIN(INITIAL);
			break;
		case CHAR:
			BEGIN(INITIAL);
			break;
	 }
	}
}

