enum operations {
	SIMPLE_BNOP = 0,
	IDENT_OP = 1,
	SIMPLE_UNOP = 2,
	TYPE_OP = 3,
	CONST_CHAR_OP = 4,
	CONST_STR_OP = 5,
	CONST_INT_OP = 6,
	CONST_DBL_OP =7,
	CONST_FLT_OP =8,
	SELECT_OP = 9,
	TERNARY_OP=10,
	FNCALL_OP=12,
	CAST_OP=13,
	MOV = 260,
	LOAD = 261,
	STORE = 262,
	LEA = 263	
};
